include:
  - project: 'deploy/dev'
    file: '/go-app-v2.yml'
    ref: 'main'

lint dev:
  extends: .lint-dev

test dev:
  extends: .test-dev

build dev:
  extends: .build-dev

deploy dev:
  extends: .deploy-dev
  variables:
    DB_PORT: 54407

cleanup:
  extends: .cleanup

release:
  extends: .release

merge:
  extends: .merge

build:
  extends: .build-shell

migration-build:
  extends: .migration-build

helm-lint:
  extends: .helm-lint

deploy:
  extends: .deploy

rollout:
  extends: .rollout
