include:
  - project: "qcloudy/ci-cd/calendaria-pipelines"
    file: "golang-pipeline.yaml"
  
build:
  extends: .build

migration-build:
  extends: .migration-build

helm-lint:
  extends: .helm-lint

deploy:
  extends: .deploy
