services:
  tenants:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: dev
    container_name: tenants
    restart: unless-stopped
    environment:
      - SERVICE_NAME=tenants
      - CONSUL_ADDRESS=${CONSUL_ADDRESS}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
      - DEBUG=true
      - AUTOMIGRATE=true
