// Code generated by ifacemaker; DO NOT EDIT.

package data

import (
	"context"

	rbac_v1 "github.com/makesalekz/rbac/api/rbac/v1"
)

// IRbacRemote ...
type IRbacRemote interface {
	AssignRoles(ctx context.Context, assigns ...*rbac_v1.AssignRoleRequest) error
}
