// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/groups.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ent "github.com/makesalekz/tenants/ent"
	data "github.com/makesalekz/tenants/internal/data"
	utils_v1 "github.com/makesalekz/utils/api/utils/v1"
)

// MockGroupsRepo is a mock of GroupsRepo interface.
type MockGroupsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGroupsRepoMockRecorder
}

// MockGroupsRepoMockRecorder is the mock recorder for MockGroupsRepo.
type MockGroupsRepoMockRecorder struct {
	mock *MockGroupsRepo
}

// NewMockGroupsRepo creates a new mock instance.
func NewMockGroupsRepo(ctrl *gomock.Controller) *MockGroupsRepo {
	mock := &MockGroupsRepo{ctrl: ctrl}
	mock.recorder = &MockGroupsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupsRepo) EXPECT() *MockGroupsRepoMockRecorder {
	return m.recorder
}

// AddMembersToGroup mocks base method.
func (m *MockGroupsRepo) AddMembersToGroup(ctx context.Context, group *ent.Group, membersIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMembersToGroup", ctx, group, membersIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMembersToGroup indicates an expected call of AddMembersToGroup.
func (mr *MockGroupsRepoMockRecorder) AddMembersToGroup(ctx, group, membersIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMembersToGroup", reflect.TypeOf((*MockGroupsRepo)(nil).AddMembersToGroup), ctx, group, membersIDs)
}

// CountListGroups mocks base method.
func (m *MockGroupsRepo) CountListGroups(ctx context.Context, filter data.GroupsListFilter) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountListGroups", ctx, filter)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountListGroups indicates an expected call of CountListGroups.
func (mr *MockGroupsRepoMockRecorder) CountListGroups(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountListGroups", reflect.TypeOf((*MockGroupsRepo)(nil).CountListGroups), ctx, filter)
}

// CreateGroup mocks base method.
func (m *MockGroupsRepo) CreateGroup(ctx context.Context, actorID int64, dto data.CreateGroupDto) (*ent.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateGroup", ctx, actorID, dto)
	ret0, _ := ret[0].(*ent.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateGroup indicates an expected call of CreateGroup.
func (mr *MockGroupsRepoMockRecorder) CreateGroup(ctx, actorID, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateGroup", reflect.TypeOf((*MockGroupsRepo)(nil).CreateGroup), ctx, actorID, dto)
}

// DeleteGroup mocks base method.
func (m *MockGroupsRepo) DeleteGroup(ctx context.Context, group *ent.Group) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteGroup", ctx, group)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteGroup indicates an expected call of DeleteGroup.
func (mr *MockGroupsRepoMockRecorder) DeleteGroup(ctx, group interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteGroup", reflect.TypeOf((*MockGroupsRepo)(nil).DeleteGroup), ctx, group)
}

// GetGroup mocks base method.
func (m *MockGroupsRepo) GetGroup(ctx context.Context, tenantID, groupID int64) (*ent.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroup", ctx, tenantID, groupID)
	ret0, _ := ret[0].(*ent.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroup indicates an expected call of GetGroup.
func (mr *MockGroupsRepoMockRecorder) GetGroup(ctx, tenantID, groupID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroup", reflect.TypeOf((*MockGroupsRepo)(nil).GetGroup), ctx, tenantID, groupID)
}

// ListGroups mocks base method.
func (m *MockGroupsRepo) ListGroups(ctx context.Context, filter data.GroupsListFilter, sort *utils_v1.SortRequest, paginate *utils_v1.PaginateRequest) ([]*ent.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListGroups", ctx, filter, sort, paginate)
	ret0, _ := ret[0].([]*ent.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListGroups indicates an expected call of ListGroups.
func (mr *MockGroupsRepoMockRecorder) ListGroups(ctx, filter, sort, paginate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListGroups", reflect.TypeOf((*MockGroupsRepo)(nil).ListGroups), ctx, filter, sort, paginate)
}

// RemoveMembersFromGroup mocks base method.
func (m *MockGroupsRepo) RemoveMembersFromGroup(ctx context.Context, group *ent.Group, membersIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMembersFromGroup", ctx, group, membersIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMembersFromGroup indicates an expected call of RemoveMembersFromGroup.
func (mr *MockGroupsRepoMockRecorder) RemoveMembersFromGroup(ctx, group, membersIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMembersFromGroup", reflect.TypeOf((*MockGroupsRepo)(nil).RemoveMembersFromGroup), ctx, group, membersIDs)
}

// UpdateGroup mocks base method.
func (m *MockGroupsRepo) UpdateGroup(ctx context.Context, group *ent.Group, dto data.UpdateGroupDto) (*ent.Group, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateGroup", ctx, group, dto)
	ret0, _ := ret[0].(*ent.Group)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateGroup indicates an expected call of UpdateGroup.
func (mr *MockGroupsRepoMockRecorder) UpdateGroup(ctx, group, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGroup", reflect.TypeOf((*MockGroupsRepo)(nil).UpdateGroup), ctx, group, dto)
}
