// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/invites.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	ent "github.com/makesalekz/tenants/ent"
	enum "github.com/makesalekz/tenants/ent/enum"
	data "github.com/makesalekz/tenants/internal/data"
	utils_v1 "github.com/makesalekz/utils/api/utils/v1"
)

// MockInvitesRepo is a mock of InvitesRepo interface.
type MockInvitesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockInvitesRepoMockRecorder
}

// MockInvitesRepoMockRecorder is the mock recorder for MockInvitesRepo.
type MockInvitesRepoMockRecorder struct {
	mock *MockInvitesRepo
}

// NewMockInvitesRepo creates a new mock instance.
func NewMockInvitesRepo(ctrl *gomock.Controller) *MockInvitesRepo {
	mock := &MockInvitesRepo{ctrl: ctrl}
	mock.recorder = &MockInvitesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvitesRepo) EXPECT() *MockInvitesRepoMockRecorder {
	return m.recorder
}

// AcceptInvite mocks base method.
func (m *MockInvitesRepo) AcceptInvite(ctx context.Context, actorID int64, invite *ent.Invite) (*ent.Invite, *ent.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptInvite", ctx, actorID, invite)
	ret0, _ := ret[0].(*ent.Invite)
	ret1, _ := ret[1].(*ent.Member)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AcceptInvite indicates an expected call of AcceptInvite.
func (mr *MockInvitesRepoMockRecorder) AcceptInvite(ctx, actorID, invite interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptInvite", reflect.TypeOf((*MockInvitesRepo)(nil).AcceptInvite), ctx, actorID, invite)
}

// CountListInvites mocks base method.
func (m *MockInvitesRepo) CountListInvites(ctx context.Context, filter data.InvitesListFilter) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountListInvites", ctx, filter)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountListInvites indicates an expected call of CountListInvites.
func (mr *MockInvitesRepoMockRecorder) CountListInvites(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountListInvites", reflect.TypeOf((*MockInvitesRepo)(nil).CountListInvites), ctx, filter)
}

// CreateInvites mocks base method.
func (m *MockInvitesRepo) CreateInvites(ctx context.Context, tenantID int64, dtos []data.InviteDto) ([]*ent.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvites", ctx, tenantID, dtos)
	ret0, _ := ret[0].([]*ent.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInvites indicates an expected call of CreateInvites.
func (mr *MockInvitesRepoMockRecorder) CreateInvites(ctx, tenantID, dtos interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvites", reflect.TypeOf((*MockInvitesRepo)(nil).CreateInvites), ctx, tenantID, dtos)
}

// DeleteInvite mocks base method.
func (m *MockInvitesRepo) DeleteInvite(ctx context.Context, tenantID, inviteID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInvite", ctx, tenantID, inviteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInvite indicates an expected call of DeleteInvite.
func (mr *MockInvitesRepoMockRecorder) DeleteInvite(ctx, tenantID, inviteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInvite", reflect.TypeOf((*MockInvitesRepo)(nil).DeleteInvite), ctx, tenantID, inviteID)
}

// GetInvite mocks base method.
func (m *MockInvitesRepo) GetInvite(ctx context.Context, tenantID, inviteID int64) (*ent.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvite", ctx, tenantID, inviteID)
	ret0, _ := ret[0].(*ent.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInvite indicates an expected call of GetInvite.
func (mr *MockInvitesRepoMockRecorder) GetInvite(ctx, tenantID, inviteID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvite", reflect.TypeOf((*MockInvitesRepo)(nil).GetInvite), ctx, tenantID, inviteID)
}

// GetInviteByCode mocks base method.
func (m *MockInvitesRepo) GetInviteByCode(ctx context.Context, inviteID int64, code uuid.UUID) (*ent.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInviteByCode", ctx, inviteID, code)
	ret0, _ := ret[0].(*ent.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInviteByCode indicates an expected call of GetInviteByCode.
func (mr *MockInvitesRepoMockRecorder) GetInviteByCode(ctx, inviteID, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInviteByCode", reflect.TypeOf((*MockInvitesRepo)(nil).GetInviteByCode), ctx, inviteID, code)
}

// ListInvites mocks base method.
func (m *MockInvitesRepo) ListInvites(ctx context.Context, filter data.InvitesListFilter, sort *utils_v1.SortRequest, paginate *utils_v1.PaginateRequest) ([]*ent.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvites", ctx, filter, sort, paginate)
	ret0, _ := ret[0].([]*ent.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvites indicates an expected call of ListInvites.
func (mr *MockInvitesRepoMockRecorder) ListInvites(ctx, filter, sort, paginate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvites", reflect.TypeOf((*MockInvitesRepo)(nil).ListInvites), ctx, filter, sort, paginate)
}

// UpdateInviteStatus mocks base method.
func (m *MockInvitesRepo) UpdateInviteStatus(ctx context.Context, invite *ent.Invite, status enum.InviteStatus) (*ent.Invite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInviteStatus", ctx, invite, status)
	ret0, _ := ret[0].(*ent.Invite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInviteStatus indicates an expected call of UpdateInviteStatus.
func (mr *MockInvitesRepoMockRecorder) UpdateInviteStatus(ctx, invite, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInviteStatus", reflect.TypeOf((*MockInvitesRepo)(nil).UpdateInviteStatus), ctx, invite, status)
}
