// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/stores.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ent "gitlab.calendaria.team/services/tenants/ent"
	data "gitlab.calendaria.team/services/tenants/internal/data"
	utils_v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
)

// MockStoresRepo is a mock of StoresRepo interface.
type MockStoresRepo struct {
	ctrl     *gomock.Controller
	recorder *MockStoresRepoMockRecorder
}

// MockStoresRepoMockRecorder is the mock recorder for MockStoresRepo.
type MockStoresRepoMockRecorder struct {
	mock *MockStoresRepo
}

// NewMockStoresRepo creates a new mock instance.
func NewMockStoresRepo(ctrl *gomock.Controller) *MockStoresRepo {
	mock := &MockStoresRepo{ctrl: ctrl}
	mock.recorder = &MockStoresRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoresRepo) EXPECT() *MockStoresRepoMockRecorder {
	return m.recorder
}

// CountListStores mocks base method.
func (m *MockStoresRepo) CountListStores(ctx context.Context, filter data.StoresListFilter) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountListStores", ctx, filter)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountListStores indicates an expected call of CountListStores.
func (mr *MockStoresRepoMockRecorder) CountListStores(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountListStores", reflect.TypeOf((*MockStoresRepo)(nil).CountListStores), ctx, filter)
}

// CreateStore mocks base method.
func (m *MockStoresRepo) CreateStore(ctx context.Context, dto data.StoreDto) (*ent.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStore", ctx, dto)
	ret0, _ := ret[0].(*ent.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStore indicates an expected call of CreateStore.
func (mr *MockStoresRepoMockRecorder) CreateStore(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStore", reflect.TypeOf((*MockStoresRepo)(nil).CreateStore), ctx, dto)
}

// DeleteStore mocks base method.
func (m *MockStoresRepo) DeleteStore(ctx context.Context, id, tenantID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStore", ctx, id, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStore indicates an expected call of DeleteStore.
func (mr *MockStoresRepoMockRecorder) DeleteStore(ctx, id, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStore", reflect.TypeOf((*MockStoresRepo)(nil).DeleteStore), ctx, id, tenantID)
}

// GetStore mocks base method.
func (m *MockStoresRepo) GetStore(ctx context.Context, id, tenantID int64) (*ent.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStore", ctx, id, tenantID)
	ret0, _ := ret[0].(*ent.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStore indicates an expected call of GetStore.
func (mr *MockStoresRepoMockRecorder) GetStore(ctx, id, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStore", reflect.TypeOf((*MockStoresRepo)(nil).GetStore), ctx, id, tenantID)
}

// ListStores mocks base method.
func (m *MockStoresRepo) ListStores(ctx context.Context, filter data.StoresListFilter, paginate *utils_v1.PaginateRequest) ([]*ent.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStores", ctx, filter, paginate)
	ret0, _ := ret[0].([]*ent.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStores indicates an expected call of ListStores.
func (mr *MockStoresRepoMockRecorder) ListStores(ctx, filter, paginate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStores", reflect.TypeOf((*MockStoresRepo)(nil).ListStores), ctx, filter, paginate)
}

// SetResponsible mocks base method.
func (m *MockStoresRepo) SetResponsible(ctx context.Context, storeID, tenantID, memberID int64) (*ent.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetResponsible", ctx, storeID, tenantID, memberID)
	ret0, _ := ret[0].(*ent.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetResponsible indicates an expected call of SetResponsible.
func (mr *MockStoresRepoMockRecorder) SetResponsible(ctx, storeID, tenantID, memberID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetResponsible", reflect.TypeOf((*MockStoresRepo)(nil).SetResponsible), ctx, storeID, tenantID, memberID)
}

// UpdateStore mocks base method.
func (m *MockStoresRepo) UpdateStore(ctx context.Context, dto data.StoreDto) (*ent.Store, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStore", ctx, dto)
	ret0, _ := ret[0].(*ent.Store)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStore indicates an expected call of UpdateStore.
func (mr *MockStoresRepoMockRecorder) UpdateStore(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStore", reflect.TypeOf((*MockStoresRepo)(nil).UpdateStore), ctx, dto)
}
