// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/tenants.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ent "gitlab.calendaria.team/services/tenants/ent"
	data "gitlab.calendaria.team/services/tenants/internal/data"
	utils_v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
)

// MockTenantsRepo is a mock of TenantsRepo interface.
type MockTenantsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTenantsRepoMockRecorder
}

// MockTenantsRepoMockRecorder is the mock recorder for MockTenantsRepo.
type MockTenantsRepoMockRecorder struct {
	mock *MockTenantsRepo
}

// NewMockTenantsRepo creates a new mock instance.
func NewMockTenantsRepo(ctrl *gomock.Controller) *MockTenantsRepo {
	mock := &MockTenantsRepo{ctrl: ctrl}
	mock.recorder = &MockTenantsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantsRepo) EXPECT() *MockTenantsRepoMockRecorder {
	return m.recorder
}

// CountListTenants mocks base method.
func (m *MockTenantsRepo) CountListTenants(ctx context.Context, filter data.TenantsListFilter) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountListTenants", ctx, filter)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountListTenants indicates an expected call of CountListTenants.
func (mr *MockTenantsRepoMockRecorder) CountListTenants(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountListTenants", reflect.TypeOf((*MockTenantsRepo)(nil).CountListTenants), ctx, filter)
}

// CreateTenant mocks base method.
func (m *MockTenantsRepo) CreateTenant(ctx context.Context, dto data.TenantDto) (*ent.Tenant, *ent.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTenant", ctx, dto)
	ret0, _ := ret[0].(*ent.Tenant)
	ret1, _ := ret[1].(*ent.Member)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateTenant indicates an expected call of CreateTenant.
func (mr *MockTenantsRepoMockRecorder) CreateTenant(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTenant", reflect.TypeOf((*MockTenantsRepo)(nil).CreateTenant), ctx, dto)
}

// DeleteTenant mocks base method.
func (m *MockTenantsRepo) DeleteTenant(ctx context.Context, tenantID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenant", ctx, tenantID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTenant indicates an expected call of DeleteTenant.
func (mr *MockTenantsRepoMockRecorder) DeleteTenant(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenant", reflect.TypeOf((*MockTenantsRepo)(nil).DeleteTenant), ctx, tenantID)
}

// DeleteUsersTenants mocks base method.
func (m *MockTenantsRepo) DeleteUsersTenants(ctx context.Context, usersIDs []int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUsersTenants", ctx, usersIDs)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUsersTenants indicates an expected call of DeleteUsersTenants.
func (mr *MockTenantsRepoMockRecorder) DeleteUsersTenants(ctx, usersIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUsersTenants", reflect.TypeOf((*MockTenantsRepo)(nil).DeleteUsersTenants), ctx, usersIDs)
}

// GetTenant mocks base method.
func (m *MockTenantsRepo) GetTenant(ctx context.Context, tenantID int64) (*ent.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenant", ctx, tenantID)
	ret0, _ := ret[0].(*ent.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTenant indicates an expected call of GetTenant.
func (mr *MockTenantsRepoMockRecorder) GetTenant(ctx, tenantID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenant", reflect.TypeOf((*MockTenantsRepo)(nil).GetTenant), ctx, tenantID)
}

// ListTenants mocks base method.
func (m *MockTenantsRepo) ListTenants(ctx context.Context, filter data.TenantsListFilter, paginate *utils_v1.PaginateRequest) ([]*ent.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTenants", ctx, filter, paginate)
	ret0, _ := ret[0].([]*ent.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTenants indicates an expected call of ListTenants.
func (mr *MockTenantsRepoMockRecorder) ListTenants(ctx, filter, paginate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTenants", reflect.TypeOf((*MockTenantsRepo)(nil).ListTenants), ctx, filter, paginate)
}

// UpdateTenant mocks base method.
func (m *MockTenantsRepo) UpdateTenant(ctx context.Context, dto data.TenantDto) (*ent.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTenant", ctx, dto)
	ret0, _ := ret[0].(*ent.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTenant indicates an expected call of UpdateTenant.
func (mr *MockTenantsRepoMockRecorder) UpdateTenant(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTenant", reflect.TypeOf((*MockTenantsRepo)(nil).UpdateTenant), ctx, dto)
}
