// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gitlab.calendaria.team/services/tenants/ent/group"
	"gitlab.calendaria.team/services/tenants/ent/invite"
	"gitlab.calendaria.team/services/tenants/ent/member"
	"gitlab.calendaria.team/services/tenants/ent/predicate"
	"gitlab.calendaria.team/services/tenants/ent/store"
	"gitlab.calendaria.team/services/tenants/ent/tenant"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 5)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   group.Table,
			Columns: group.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: group.FieldID,
			},
		},
		Type: "Group",
		Fields: map[string]*sqlgraph.FieldSpec{
			group.FieldCreatedAt:   {Type: field.TypeTime, Column: group.FieldCreatedAt},
			group.FieldUpdatedAt:   {Type: field.TypeTime, Column: group.FieldUpdatedAt},
			group.FieldDeletedAt:   {Type: field.TypeTime, Column: group.FieldDeletedAt},
			group.FieldIdentityID:  {Type: field.TypeUUID, Column: group.FieldIdentityID},
			group.FieldTenantID:    {Type: field.TypeInt64, Column: group.FieldTenantID},
			group.FieldName:        {Type: field.TypeString, Column: group.FieldName},
			group.FieldDescription: {Type: field.TypeString, Column: group.FieldDescription},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   invite.Table,
			Columns: invite.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: invite.FieldID,
			},
		},
		Type: "Invite",
		Fields: map[string]*sqlgraph.FieldSpec{
			invite.FieldTenantID:   {Type: field.TypeInt64, Column: invite.FieldTenantID},
			invite.FieldCode:       {Type: field.TypeUUID, Column: invite.FieldCode},
			invite.FieldEmail:      {Type: field.TypeString, Column: invite.FieldEmail},
			invite.FieldUserID:     {Type: field.TypeInt64, Column: invite.FieldUserID},
			invite.FieldStatus:     {Type: field.TypeEnum, Column: invite.FieldStatus},
			invite.FieldCreatedAt:  {Type: field.TypeTime, Column: invite.FieldCreatedAt},
			invite.FieldUpdatedAt:  {Type: field.TypeTime, Column: invite.FieldUpdatedAt},
			invite.FieldRoleID:     {Type: field.TypeInt64, Column: invite.FieldRoleID},
			invite.FieldResource:   {Type: field.TypeString, Column: invite.FieldResource},
			invite.FieldResourceID: {Type: field.TypeInt64, Column: invite.FieldResourceID},
		},
	}
	graph.Nodes[2] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   member.Table,
			Columns: member.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: member.FieldID,
			},
		},
		Type: "Member",
		Fields: map[string]*sqlgraph.FieldSpec{
			member.FieldDeletedAt:  {Type: field.TypeTime, Column: member.FieldDeletedAt},
			member.FieldIdentityID: {Type: field.TypeUUID, Column: member.FieldIdentityID},
			member.FieldTenantID:   {Type: field.TypeInt64, Column: member.FieldTenantID},
			member.FieldUserID:     {Type: field.TypeInt64, Column: member.FieldUserID},
			member.FieldCreatedAt:  {Type: field.TypeTime, Column: member.FieldCreatedAt},
		},
	}
	graph.Nodes[3] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   store.Table,
			Columns: store.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: store.FieldID,
			},
		},
		Type: "Store",
		Fields: map[string]*sqlgraph.FieldSpec{
			store.FieldDeletedAt:     {Type: field.TypeTime, Column: store.FieldDeletedAt},
			store.FieldTenantID:      {Type: field.TypeInt64, Column: store.FieldTenantID},
			store.FieldName:          {Type: field.TypeString, Column: store.FieldName},
			store.FieldAddress:       {Type: field.TypeString, Column: store.FieldAddress},
			store.FieldLat:           {Type: field.TypeFloat64, Column: store.FieldLat},
			store.FieldLon:           {Type: field.TypeFloat64, Column: store.FieldLon},
			store.FieldPhone:         {Type: field.TypeString, Column: store.FieldPhone},
			store.FieldWorkHours:     {Type: field.TypeString, Column: store.FieldWorkHours},
			store.FieldIsActive:      {Type: field.TypeBool, Column: store.FieldIsActive},
			store.FieldResponsibleID: {Type: field.TypeInt64, Column: store.FieldResponsibleID},
			store.FieldCreatedAt:     {Type: field.TypeTime, Column: store.FieldCreatedAt},
			store.FieldUpdatedAt:     {Type: field.TypeTime, Column: store.FieldUpdatedAt},
		},
	}
	graph.Nodes[4] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   tenant.Table,
			Columns: tenant.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: tenant.FieldID,
			},
		},
		Type: "Tenant",
		Fields: map[string]*sqlgraph.FieldSpec{
			tenant.FieldDeletedAt:  {Type: field.TypeTime, Column: tenant.FieldDeletedAt},
			tenant.FieldOwnerID:    {Type: field.TypeInt64, Column: tenant.FieldOwnerID},
			tenant.FieldName:       {Type: field.TypeString, Column: tenant.FieldName},
			tenant.FieldReferredBy: {Type: field.TypeInt64, Column: tenant.FieldReferredBy},
			tenant.FieldCreatedAt:  {Type: field.TypeTime, Column: tenant.FieldCreatedAt},
			tenant.FieldUpdatedAt:  {Type: field.TypeTime, Column: tenant.FieldUpdatedAt},
			tenant.FieldType:       {Type: field.TypeString, Column: tenant.FieldType},
		},
	}
	graph.MustAddE(
		"tenant",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   group.TenantTable,
			Columns: []string{group.TenantColumn},
			Bidi:    false,
		},
		"Group",
		"Tenant",
	)
	graph.MustAddE(
		"members",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   group.MembersTable,
			Columns: group.MembersPrimaryKey,
			Bidi:    false,
		},
		"Group",
		"Member",
	)
	graph.MustAddE(
		"tenant",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.TenantTable,
			Columns: []string{invite.TenantColumn},
			Bidi:    false,
		},
		"Invite",
		"Tenant",
	)
	graph.MustAddE(
		"tenant",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   member.TenantTable,
			Columns: []string{member.TenantColumn},
			Bidi:    false,
		},
		"Member",
		"Tenant",
	)
	graph.MustAddE(
		"groups",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   member.GroupsTable,
			Columns: member.GroupsPrimaryKey,
			Bidi:    false,
		},
		"Member",
		"Group",
	)
	graph.MustAddE(
		"tenant",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   store.TenantTable,
			Columns: []string{store.TenantColumn},
			Bidi:    false,
		},
		"Store",
		"Tenant",
	)
	graph.MustAddE(
		"members",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembersTable,
			Columns: []string{tenant.MembersColumn},
			Bidi:    false,
		},
		"Tenant",
		"Member",
	)
	graph.MustAddE(
		"groups",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.GroupsTable,
			Columns: []string{tenant.GroupsColumn},
			Bidi:    false,
		},
		"Tenant",
		"Group",
	)
	graph.MustAddE(
		"invites",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.InvitesTable,
			Columns: []string{tenant.InvitesColumn},
			Bidi:    false,
		},
		"Tenant",
		"Invite",
	)
	graph.MustAddE(
		"stores",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.StoresTable,
			Columns: []string{tenant.StoresColumn},
			Bidi:    false,
		},
		"Tenant",
		"Store",
	)
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (gq *GroupQuery) addPredicate(pred func(s *sql.Selector)) {
	gq.predicates = append(gq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the GroupQuery builder.
func (gq *GroupQuery) Filter() *GroupFilter {
	return &GroupFilter{config: gq.config, predicateAdder: gq}
}

// addPredicate implements the predicateAdder interface.
func (m *GroupMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the GroupMutation builder.
func (m *GroupMutation) Filter() *GroupFilter {
	return &GroupFilter{config: m.config, predicateAdder: m}
}

// GroupFilter provides a generic filtering capability at runtime for GroupQuery.
type GroupFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *GroupFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *GroupFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(group.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *GroupFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(group.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *GroupFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(group.FieldUpdatedAt))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *GroupFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(group.FieldDeletedAt))
}

// WhereIdentityID applies the entql [16]byte predicate on the identity_id field.
func (f *GroupFilter) WhereIdentityID(p entql.ValueP) {
	f.Where(p.Field(group.FieldIdentityID))
}

// WhereTenantID applies the entql int64 predicate on the tenant_id field.
func (f *GroupFilter) WhereTenantID(p entql.Int64P) {
	f.Where(p.Field(group.FieldTenantID))
}

// WhereName applies the entql string predicate on the name field.
func (f *GroupFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(group.FieldName))
}

// WhereDescription applies the entql string predicate on the description field.
func (f *GroupFilter) WhereDescription(p entql.StringP) {
	f.Where(p.Field(group.FieldDescription))
}

// WhereHasTenant applies a predicate to check if query has an edge tenant.
func (f *GroupFilter) WhereHasTenant() {
	f.Where(entql.HasEdge("tenant"))
}

// WhereHasTenantWith applies a predicate to check if query has an edge tenant with a given conditions (other predicates).
func (f *GroupFilter) WhereHasTenantWith(preds ...predicate.Tenant) {
	f.Where(entql.HasEdgeWith("tenant", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasMembers applies a predicate to check if query has an edge members.
func (f *GroupFilter) WhereHasMembers() {
	f.Where(entql.HasEdge("members"))
}

// WhereHasMembersWith applies a predicate to check if query has an edge members with a given conditions (other predicates).
func (f *GroupFilter) WhereHasMembersWith(preds ...predicate.Member) {
	f.Where(entql.HasEdgeWith("members", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (iq *InviteQuery) addPredicate(pred func(s *sql.Selector)) {
	iq.predicates = append(iq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the InviteQuery builder.
func (iq *InviteQuery) Filter() *InviteFilter {
	return &InviteFilter{config: iq.config, predicateAdder: iq}
}

// addPredicate implements the predicateAdder interface.
func (m *InviteMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the InviteMutation builder.
func (m *InviteMutation) Filter() *InviteFilter {
	return &InviteFilter{config: m.config, predicateAdder: m}
}

// InviteFilter provides a generic filtering capability at runtime for InviteQuery.
type InviteFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *InviteFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *InviteFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(invite.FieldID))
}

// WhereTenantID applies the entql int64 predicate on the tenant_id field.
func (f *InviteFilter) WhereTenantID(p entql.Int64P) {
	f.Where(p.Field(invite.FieldTenantID))
}

// WhereCode applies the entql [16]byte predicate on the code field.
func (f *InviteFilter) WhereCode(p entql.ValueP) {
	f.Where(p.Field(invite.FieldCode))
}

// WhereEmail applies the entql string predicate on the email field.
func (f *InviteFilter) WhereEmail(p entql.StringP) {
	f.Where(p.Field(invite.FieldEmail))
}

// WhereUserID applies the entql int64 predicate on the user_id field.
func (f *InviteFilter) WhereUserID(p entql.Int64P) {
	f.Where(p.Field(invite.FieldUserID))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *InviteFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(invite.FieldStatus))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *InviteFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(invite.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *InviteFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(invite.FieldUpdatedAt))
}

// WhereRoleID applies the entql int64 predicate on the role_id field.
func (f *InviteFilter) WhereRoleID(p entql.Int64P) {
	f.Where(p.Field(invite.FieldRoleID))
}

// WhereResource applies the entql string predicate on the resource field.
func (f *InviteFilter) WhereResource(p entql.StringP) {
	f.Where(p.Field(invite.FieldResource))
}

// WhereResourceID applies the entql int64 predicate on the resource_id field.
func (f *InviteFilter) WhereResourceID(p entql.Int64P) {
	f.Where(p.Field(invite.FieldResourceID))
}

// WhereHasTenant applies a predicate to check if query has an edge tenant.
func (f *InviteFilter) WhereHasTenant() {
	f.Where(entql.HasEdge("tenant"))
}

// WhereHasTenantWith applies a predicate to check if query has an edge tenant with a given conditions (other predicates).
func (f *InviteFilter) WhereHasTenantWith(preds ...predicate.Tenant) {
	f.Where(entql.HasEdgeWith("tenant", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (mq *MemberQuery) addPredicate(pred func(s *sql.Selector)) {
	mq.predicates = append(mq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the MemberQuery builder.
func (mq *MemberQuery) Filter() *MemberFilter {
	return &MemberFilter{config: mq.config, predicateAdder: mq}
}

// addPredicate implements the predicateAdder interface.
func (m *MemberMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the MemberMutation builder.
func (m *MemberMutation) Filter() *MemberFilter {
	return &MemberFilter{config: m.config, predicateAdder: m}
}

// MemberFilter provides a generic filtering capability at runtime for MemberQuery.
type MemberFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *MemberFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[2].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *MemberFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(member.FieldID))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *MemberFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(member.FieldDeletedAt))
}

// WhereIdentityID applies the entql [16]byte predicate on the identity_id field.
func (f *MemberFilter) WhereIdentityID(p entql.ValueP) {
	f.Where(p.Field(member.FieldIdentityID))
}

// WhereTenantID applies the entql int64 predicate on the tenant_id field.
func (f *MemberFilter) WhereTenantID(p entql.Int64P) {
	f.Where(p.Field(member.FieldTenantID))
}

// WhereUserID applies the entql int64 predicate on the user_id field.
func (f *MemberFilter) WhereUserID(p entql.Int64P) {
	f.Where(p.Field(member.FieldUserID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *MemberFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(member.FieldCreatedAt))
}

// WhereHasTenant applies a predicate to check if query has an edge tenant.
func (f *MemberFilter) WhereHasTenant() {
	f.Where(entql.HasEdge("tenant"))
}

// WhereHasTenantWith applies a predicate to check if query has an edge tenant with a given conditions (other predicates).
func (f *MemberFilter) WhereHasTenantWith(preds ...predicate.Tenant) {
	f.Where(entql.HasEdgeWith("tenant", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasGroups applies a predicate to check if query has an edge groups.
func (f *MemberFilter) WhereHasGroups() {
	f.Where(entql.HasEdge("groups"))
}

// WhereHasGroupsWith applies a predicate to check if query has an edge groups with a given conditions (other predicates).
func (f *MemberFilter) WhereHasGroupsWith(preds ...predicate.Group) {
	f.Where(entql.HasEdgeWith("groups", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (sq *StoreQuery) addPredicate(pred func(s *sql.Selector)) {
	sq.predicates = append(sq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the StoreQuery builder.
func (sq *StoreQuery) Filter() *StoreFilter {
	return &StoreFilter{config: sq.config, predicateAdder: sq}
}

// addPredicate implements the predicateAdder interface.
func (m *StoreMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the StoreMutation builder.
func (m *StoreMutation) Filter() *StoreFilter {
	return &StoreFilter{config: m.config, predicateAdder: m}
}

// StoreFilter provides a generic filtering capability at runtime for StoreQuery.
type StoreFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *StoreFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[3].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *StoreFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(store.FieldID))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *StoreFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(store.FieldDeletedAt))
}

// WhereTenantID applies the entql int64 predicate on the tenant_id field.
func (f *StoreFilter) WhereTenantID(p entql.Int64P) {
	f.Where(p.Field(store.FieldTenantID))
}

// WhereName applies the entql string predicate on the name field.
func (f *StoreFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(store.FieldName))
}

// WhereAddress applies the entql string predicate on the address field.
func (f *StoreFilter) WhereAddress(p entql.StringP) {
	f.Where(p.Field(store.FieldAddress))
}

// WhereLat applies the entql float64 predicate on the lat field.
func (f *StoreFilter) WhereLat(p entql.Float64P) {
	f.Where(p.Field(store.FieldLat))
}

// WhereLon applies the entql float64 predicate on the lon field.
func (f *StoreFilter) WhereLon(p entql.Float64P) {
	f.Where(p.Field(store.FieldLon))
}

// WherePhone applies the entql string predicate on the phone field.
func (f *StoreFilter) WherePhone(p entql.StringP) {
	f.Where(p.Field(store.FieldPhone))
}

// WhereWorkHours applies the entql string predicate on the work_hours field.
func (f *StoreFilter) WhereWorkHours(p entql.StringP) {
	f.Where(p.Field(store.FieldWorkHours))
}

// WhereIsActive applies the entql bool predicate on the is_active field.
func (f *StoreFilter) WhereIsActive(p entql.BoolP) {
	f.Where(p.Field(store.FieldIsActive))
}

// WhereResponsibleID applies the entql int64 predicate on the responsible_id field.
func (f *StoreFilter) WhereResponsibleID(p entql.Int64P) {
	f.Where(p.Field(store.FieldResponsibleID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *StoreFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(store.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *StoreFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(store.FieldUpdatedAt))
}

// WhereHasTenant applies a predicate to check if query has an edge tenant.
func (f *StoreFilter) WhereHasTenant() {
	f.Where(entql.HasEdge("tenant"))
}

// WhereHasTenantWith applies a predicate to check if query has an edge tenant with a given conditions (other predicates).
func (f *StoreFilter) WhereHasTenantWith(preds ...predicate.Tenant) {
	f.Where(entql.HasEdgeWith("tenant", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (tq *TenantQuery) addPredicate(pred func(s *sql.Selector)) {
	tq.predicates = append(tq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the TenantQuery builder.
func (tq *TenantQuery) Filter() *TenantFilter {
	return &TenantFilter{config: tq.config, predicateAdder: tq}
}

// addPredicate implements the predicateAdder interface.
func (m *TenantMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the TenantMutation builder.
func (m *TenantMutation) Filter() *TenantFilter {
	return &TenantFilter{config: m.config, predicateAdder: m}
}

// TenantFilter provides a generic filtering capability at runtime for TenantQuery.
type TenantFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *TenantFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[4].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *TenantFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(tenant.FieldID))
}

// WhereDeletedAt applies the entql time.Time predicate on the deleted_at field.
func (f *TenantFilter) WhereDeletedAt(p entql.TimeP) {
	f.Where(p.Field(tenant.FieldDeletedAt))
}

// WhereOwnerID applies the entql int64 predicate on the owner_id field.
func (f *TenantFilter) WhereOwnerID(p entql.Int64P) {
	f.Where(p.Field(tenant.FieldOwnerID))
}

// WhereName applies the entql string predicate on the name field.
func (f *TenantFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(tenant.FieldName))
}

// WhereReferredBy applies the entql int64 predicate on the referred_by field.
func (f *TenantFilter) WhereReferredBy(p entql.Int64P) {
	f.Where(p.Field(tenant.FieldReferredBy))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *TenantFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(tenant.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *TenantFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(tenant.FieldUpdatedAt))
}

// WhereType applies the entql string predicate on the type field.
func (f *TenantFilter) WhereType(p entql.StringP) {
	f.Where(p.Field(tenant.FieldType))
}

// WhereHasMembers applies a predicate to check if query has an edge members.
func (f *TenantFilter) WhereHasMembers() {
	f.Where(entql.HasEdge("members"))
}

// WhereHasMembersWith applies a predicate to check if query has an edge members with a given conditions (other predicates).
func (f *TenantFilter) WhereHasMembersWith(preds ...predicate.Member) {
	f.Where(entql.HasEdgeWith("members", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasGroups applies a predicate to check if query has an edge groups.
func (f *TenantFilter) WhereHasGroups() {
	f.Where(entql.HasEdge("groups"))
}

// WhereHasGroupsWith applies a predicate to check if query has an edge groups with a given conditions (other predicates).
func (f *TenantFilter) WhereHasGroupsWith(preds ...predicate.Group) {
	f.Where(entql.HasEdgeWith("groups", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasInvites applies a predicate to check if query has an edge invites.
func (f *TenantFilter) WhereHasInvites() {
	f.Where(entql.HasEdge("invites"))
}

// WhereHasInvitesWith applies a predicate to check if query has an edge invites with a given conditions (other predicates).
func (f *TenantFilter) WhereHasInvitesWith(preds ...predicate.Invite) {
	f.Where(entql.HasEdgeWith("invites", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasStores applies a predicate to check if query has an edge stores.
func (f *TenantFilter) WhereHasStores() {
	f.Where(entql.HasEdge("stores"))
}

// WhereHasStoresWith applies a predicate to check if query has an edge stores with a given conditions (other predicates).
func (f *TenantFilter) WhereHasStoresWith(preds ...predicate.Store) {
	f.Where(entql.HasEdgeWith("stores", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}
