// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/tenants/ent/enum"
	"gitlab.calendaria.team/services/tenants/ent/invite"
	"gitlab.calendaria.team/services/tenants/ent/predicate"
)

// InviteUpdate is the builder for updating Invite entities.
type InviteUpdate struct {
	config
	hooks     []Hook
	mutation  *InviteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the InviteUpdate builder.
func (iu *InviteUpdate) Where(ps ...predicate.Invite) *InviteUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetUserID sets the "user_id" field.
func (iu *InviteUpdate) SetUserID(i int64) *InviteUpdate {
	iu.mutation.ResetUserID()
	iu.mutation.SetUserID(i)
	return iu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableUserID(i *int64) *InviteUpdate {
	if i != nil {
		iu.SetUserID(*i)
	}
	return iu
}

// AddUserID adds i to the "user_id" field.
func (iu *InviteUpdate) AddUserID(i int64) *InviteUpdate {
	iu.mutation.AddUserID(i)
	return iu
}

// ClearUserID clears the value of the "user_id" field.
func (iu *InviteUpdate) ClearUserID() *InviteUpdate {
	iu.mutation.ClearUserID()
	return iu
}

// SetStatus sets the "status" field.
func (iu *InviteUpdate) SetStatus(es enum.InviteStatus) *InviteUpdate {
	iu.mutation.SetStatus(es)
	return iu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableStatus(es *enum.InviteStatus) *InviteUpdate {
	if es != nil {
		iu.SetStatus(*es)
	}
	return iu
}

// SetUpdatedAt sets the "updated_at" field.
func (iu *InviteUpdate) SetUpdatedAt(t time.Time) *InviteUpdate {
	iu.mutation.SetUpdatedAt(t)
	return iu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableUpdatedAt(t *time.Time) *InviteUpdate {
	if t != nil {
		iu.SetUpdatedAt(*t)
	}
	return iu
}

// SetRoleID sets the "role_id" field.
func (iu *InviteUpdate) SetRoleID(i int64) *InviteUpdate {
	iu.mutation.ResetRoleID()
	iu.mutation.SetRoleID(i)
	return iu
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableRoleID(i *int64) *InviteUpdate {
	if i != nil {
		iu.SetRoleID(*i)
	}
	return iu
}

// AddRoleID adds i to the "role_id" field.
func (iu *InviteUpdate) AddRoleID(i int64) *InviteUpdate {
	iu.mutation.AddRoleID(i)
	return iu
}

// ClearRoleID clears the value of the "role_id" field.
func (iu *InviteUpdate) ClearRoleID() *InviteUpdate {
	iu.mutation.ClearRoleID()
	return iu
}

// SetResource sets the "resource" field.
func (iu *InviteUpdate) SetResource(s string) *InviteUpdate {
	iu.mutation.SetResource(s)
	return iu
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableResource(s *string) *InviteUpdate {
	if s != nil {
		iu.SetResource(*s)
	}
	return iu
}

// ClearResource clears the value of the "resource" field.
func (iu *InviteUpdate) ClearResource() *InviteUpdate {
	iu.mutation.ClearResource()
	return iu
}

// SetResourceID sets the "resource_id" field.
func (iu *InviteUpdate) SetResourceID(i int64) *InviteUpdate {
	iu.mutation.ResetResourceID()
	iu.mutation.SetResourceID(i)
	return iu
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (iu *InviteUpdate) SetNillableResourceID(i *int64) *InviteUpdate {
	if i != nil {
		iu.SetResourceID(*i)
	}
	return iu
}

// AddResourceID adds i to the "resource_id" field.
func (iu *InviteUpdate) AddResourceID(i int64) *InviteUpdate {
	iu.mutation.AddResourceID(i)
	return iu
}

// ClearResourceID clears the value of the "resource_id" field.
func (iu *InviteUpdate) ClearResourceID() *InviteUpdate {
	iu.mutation.ClearResourceID()
	return iu
}

// Mutation returns the InviteMutation object of the builder.
func (iu *InviteUpdate) Mutation() *InviteMutation {
	return iu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *InviteUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *InviteUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *InviteUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *InviteUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iu *InviteUpdate) check() error {
	if v, ok := iu.mutation.Status(); ok {
		if err := invite.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Invite.status": %w`, err)}
		}
	}
	if iu.mutation.TenantCleared() && len(iu.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invite.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (iu *InviteUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InviteUpdate {
	iu.modifiers = append(iu.modifiers, modifiers...)
	return iu
}

func (iu *InviteUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := iu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(invite.Table, invite.Columns, sqlgraph.NewFieldSpec(invite.FieldID, field.TypeInt64))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.UserID(); ok {
		_spec.SetField(invite.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := iu.mutation.AddedUserID(); ok {
		_spec.AddField(invite.FieldUserID, field.TypeInt64, value)
	}
	if iu.mutation.UserIDCleared() {
		_spec.ClearField(invite.FieldUserID, field.TypeInt64)
	}
	if value, ok := iu.mutation.Status(); ok {
		_spec.SetField(invite.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := iu.mutation.UpdatedAt(); ok {
		_spec.SetField(invite.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := iu.mutation.RoleID(); ok {
		_spec.SetField(invite.FieldRoleID, field.TypeInt64, value)
	}
	if value, ok := iu.mutation.AddedRoleID(); ok {
		_spec.AddField(invite.FieldRoleID, field.TypeInt64, value)
	}
	if iu.mutation.RoleIDCleared() {
		_spec.ClearField(invite.FieldRoleID, field.TypeInt64)
	}
	if value, ok := iu.mutation.Resource(); ok {
		_spec.SetField(invite.FieldResource, field.TypeString, value)
	}
	if iu.mutation.ResourceCleared() {
		_spec.ClearField(invite.FieldResource, field.TypeString)
	}
	if value, ok := iu.mutation.ResourceID(); ok {
		_spec.SetField(invite.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := iu.mutation.AddedResourceID(); ok {
		_spec.AddField(invite.FieldResourceID, field.TypeInt64, value)
	}
	if iu.mutation.ResourceIDCleared() {
		_spec.ClearField(invite.FieldResourceID, field.TypeInt64)
	}
	_spec.AddModifiers(iu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// InviteUpdateOne is the builder for updating a single Invite entity.
type InviteUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *InviteMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (iuo *InviteUpdateOne) SetUserID(i int64) *InviteUpdateOne {
	iuo.mutation.ResetUserID()
	iuo.mutation.SetUserID(i)
	return iuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableUserID(i *int64) *InviteUpdateOne {
	if i != nil {
		iuo.SetUserID(*i)
	}
	return iuo
}

// AddUserID adds i to the "user_id" field.
func (iuo *InviteUpdateOne) AddUserID(i int64) *InviteUpdateOne {
	iuo.mutation.AddUserID(i)
	return iuo
}

// ClearUserID clears the value of the "user_id" field.
func (iuo *InviteUpdateOne) ClearUserID() *InviteUpdateOne {
	iuo.mutation.ClearUserID()
	return iuo
}

// SetStatus sets the "status" field.
func (iuo *InviteUpdateOne) SetStatus(es enum.InviteStatus) *InviteUpdateOne {
	iuo.mutation.SetStatus(es)
	return iuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableStatus(es *enum.InviteStatus) *InviteUpdateOne {
	if es != nil {
		iuo.SetStatus(*es)
	}
	return iuo
}

// SetUpdatedAt sets the "updated_at" field.
func (iuo *InviteUpdateOne) SetUpdatedAt(t time.Time) *InviteUpdateOne {
	iuo.mutation.SetUpdatedAt(t)
	return iuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableUpdatedAt(t *time.Time) *InviteUpdateOne {
	if t != nil {
		iuo.SetUpdatedAt(*t)
	}
	return iuo
}

// SetRoleID sets the "role_id" field.
func (iuo *InviteUpdateOne) SetRoleID(i int64) *InviteUpdateOne {
	iuo.mutation.ResetRoleID()
	iuo.mutation.SetRoleID(i)
	return iuo
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableRoleID(i *int64) *InviteUpdateOne {
	if i != nil {
		iuo.SetRoleID(*i)
	}
	return iuo
}

// AddRoleID adds i to the "role_id" field.
func (iuo *InviteUpdateOne) AddRoleID(i int64) *InviteUpdateOne {
	iuo.mutation.AddRoleID(i)
	return iuo
}

// ClearRoleID clears the value of the "role_id" field.
func (iuo *InviteUpdateOne) ClearRoleID() *InviteUpdateOne {
	iuo.mutation.ClearRoleID()
	return iuo
}

// SetResource sets the "resource" field.
func (iuo *InviteUpdateOne) SetResource(s string) *InviteUpdateOne {
	iuo.mutation.SetResource(s)
	return iuo
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableResource(s *string) *InviteUpdateOne {
	if s != nil {
		iuo.SetResource(*s)
	}
	return iuo
}

// ClearResource clears the value of the "resource" field.
func (iuo *InviteUpdateOne) ClearResource() *InviteUpdateOne {
	iuo.mutation.ClearResource()
	return iuo
}

// SetResourceID sets the "resource_id" field.
func (iuo *InviteUpdateOne) SetResourceID(i int64) *InviteUpdateOne {
	iuo.mutation.ResetResourceID()
	iuo.mutation.SetResourceID(i)
	return iuo
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (iuo *InviteUpdateOne) SetNillableResourceID(i *int64) *InviteUpdateOne {
	if i != nil {
		iuo.SetResourceID(*i)
	}
	return iuo
}

// AddResourceID adds i to the "resource_id" field.
func (iuo *InviteUpdateOne) AddResourceID(i int64) *InviteUpdateOne {
	iuo.mutation.AddResourceID(i)
	return iuo
}

// ClearResourceID clears the value of the "resource_id" field.
func (iuo *InviteUpdateOne) ClearResourceID() *InviteUpdateOne {
	iuo.mutation.ClearResourceID()
	return iuo
}

// Mutation returns the InviteMutation object of the builder.
func (iuo *InviteUpdateOne) Mutation() *InviteMutation {
	return iuo.mutation
}

// Where appends a list predicates to the InviteUpdate builder.
func (iuo *InviteUpdateOne) Where(ps ...predicate.Invite) *InviteUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *InviteUpdateOne) Select(field string, fields ...string) *InviteUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Invite entity.
func (iuo *InviteUpdateOne) Save(ctx context.Context) (*Invite, error) {
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *InviteUpdateOne) SaveX(ctx context.Context) *Invite {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *InviteUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *InviteUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iuo *InviteUpdateOne) check() error {
	if v, ok := iuo.mutation.Status(); ok {
		if err := invite.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Invite.status": %w`, err)}
		}
	}
	if iuo.mutation.TenantCleared() && len(iuo.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Invite.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (iuo *InviteUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InviteUpdateOne {
	iuo.modifiers = append(iuo.modifiers, modifiers...)
	return iuo
}

func (iuo *InviteUpdateOne) sqlSave(ctx context.Context) (_node *Invite, err error) {
	if err := iuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invite.Table, invite.Columns, sqlgraph.NewFieldSpec(invite.FieldID, field.TypeInt64))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Invite.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invite.FieldID)
		for _, f := range fields {
			if !invite.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != invite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.UserID(); ok {
		_spec.SetField(invite.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := iuo.mutation.AddedUserID(); ok {
		_spec.AddField(invite.FieldUserID, field.TypeInt64, value)
	}
	if iuo.mutation.UserIDCleared() {
		_spec.ClearField(invite.FieldUserID, field.TypeInt64)
	}
	if value, ok := iuo.mutation.Status(); ok {
		_spec.SetField(invite.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := iuo.mutation.UpdatedAt(); ok {
		_spec.SetField(invite.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := iuo.mutation.RoleID(); ok {
		_spec.SetField(invite.FieldRoleID, field.TypeInt64, value)
	}
	if value, ok := iuo.mutation.AddedRoleID(); ok {
		_spec.AddField(invite.FieldRoleID, field.TypeInt64, value)
	}
	if iuo.mutation.RoleIDCleared() {
		_spec.ClearField(invite.FieldRoleID, field.TypeInt64)
	}
	if value, ok := iuo.mutation.Resource(); ok {
		_spec.SetField(invite.FieldResource, field.TypeString, value)
	}
	if iuo.mutation.ResourceCleared() {
		_spec.ClearField(invite.FieldResource, field.TypeString)
	}
	if value, ok := iuo.mutation.ResourceID(); ok {
		_spec.SetField(invite.FieldResourceID, field.TypeInt64, value)
	}
	if value, ok := iuo.mutation.AddedResourceID(); ok {
		_spec.AddField(invite.FieldResourceID, field.TypeInt64, value)
	}
	if iuo.mutation.ResourceIDCleared() {
		_spec.ClearField(invite.FieldResourceID, field.TypeInt64)
	}
	_spec.AddModifiers(iuo.modifiers...)
	_node = &Invite{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
