// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"gitlab.calendaria.team/services/tenants/ent/enum"
	"gitlab.calendaria.team/services/tenants/ent/invite"
	"gitlab.calendaria.team/services/tenants/ent/tenant"
)

// InviteCreate is the builder for creating a Invite entity.
type InviteCreate struct {
	config
	mutation *InviteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (ic *InviteCreate) SetTenantID(i int64) *InviteCreate {
	ic.mutation.SetTenantID(i)
	return ic
}

// SetCode sets the "code" field.
func (ic *InviteCreate) SetCode(u uuid.UUID) *InviteCreate {
	ic.mutation.SetCode(u)
	return ic
}

// SetEmail sets the "email" field.
func (ic *InviteCreate) SetEmail(s string) *InviteCreate {
	ic.mutation.SetEmail(s)
	return ic
}

// SetUserID sets the "user_id" field.
func (ic *InviteCreate) SetUserID(i int64) *InviteCreate {
	ic.mutation.SetUserID(i)
	return ic
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (ic *InviteCreate) SetNillableUserID(i *int64) *InviteCreate {
	if i != nil {
		ic.SetUserID(*i)
	}
	return ic
}

// SetStatus sets the "status" field.
func (ic *InviteCreate) SetStatus(es enum.InviteStatus) *InviteCreate {
	ic.mutation.SetStatus(es)
	return ic
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ic *InviteCreate) SetNillableStatus(es *enum.InviteStatus) *InviteCreate {
	if es != nil {
		ic.SetStatus(*es)
	}
	return ic
}

// SetCreatedAt sets the "created_at" field.
func (ic *InviteCreate) SetCreatedAt(t time.Time) *InviteCreate {
	ic.mutation.SetCreatedAt(t)
	return ic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ic *InviteCreate) SetNillableCreatedAt(t *time.Time) *InviteCreate {
	if t != nil {
		ic.SetCreatedAt(*t)
	}
	return ic
}

// SetUpdatedAt sets the "updated_at" field.
func (ic *InviteCreate) SetUpdatedAt(t time.Time) *InviteCreate {
	ic.mutation.SetUpdatedAt(t)
	return ic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ic *InviteCreate) SetNillableUpdatedAt(t *time.Time) *InviteCreate {
	if t != nil {
		ic.SetUpdatedAt(*t)
	}
	return ic
}

// SetRoleID sets the "role_id" field.
func (ic *InviteCreate) SetRoleID(i int64) *InviteCreate {
	ic.mutation.SetRoleID(i)
	return ic
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (ic *InviteCreate) SetNillableRoleID(i *int64) *InviteCreate {
	if i != nil {
		ic.SetRoleID(*i)
	}
	return ic
}

// SetResource sets the "resource" field.
func (ic *InviteCreate) SetResource(s string) *InviteCreate {
	ic.mutation.SetResource(s)
	return ic
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (ic *InviteCreate) SetNillableResource(s *string) *InviteCreate {
	if s != nil {
		ic.SetResource(*s)
	}
	return ic
}

// SetResourceID sets the "resource_id" field.
func (ic *InviteCreate) SetResourceID(i int64) *InviteCreate {
	ic.mutation.SetResourceID(i)
	return ic
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (ic *InviteCreate) SetNillableResourceID(i *int64) *InviteCreate {
	if i != nil {
		ic.SetResourceID(*i)
	}
	return ic
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (ic *InviteCreate) SetTenant(t *Tenant) *InviteCreate {
	return ic.SetTenantID(t.ID)
}

// Mutation returns the InviteMutation object of the builder.
func (ic *InviteCreate) Mutation() *InviteMutation {
	return ic.mutation
}

// Save creates the Invite in the database.
func (ic *InviteCreate) Save(ctx context.Context) (*Invite, error) {
	ic.defaults()
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *InviteCreate) SaveX(ctx context.Context) *Invite {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *InviteCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *InviteCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *InviteCreate) defaults() {
	if _, ok := ic.mutation.Status(); !ok {
		v := invite.DefaultStatus
		ic.mutation.SetStatus(v)
	}
	if _, ok := ic.mutation.CreatedAt(); !ok {
		v := invite.DefaultCreatedAt()
		ic.mutation.SetCreatedAt(v)
	}
	if _, ok := ic.mutation.UpdatedAt(); !ok {
		v := invite.DefaultUpdatedAt()
		ic.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *InviteCreate) check() error {
	if _, ok := ic.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Invite.tenant_id"`)}
	}
	if _, ok := ic.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Invite.code"`)}
	}
	if _, ok := ic.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Invite.email"`)}
	}
	if _, ok := ic.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Invite.status"`)}
	}
	if v, ok := ic.mutation.Status(); ok {
		if err := invite.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Invite.status": %w`, err)}
		}
	}
	if _, ok := ic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Invite.created_at"`)}
	}
	if _, ok := ic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Invite.updated_at"`)}
	}
	if _, ok := ic.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Invite.tenant"`)}
	}
	return nil
}

func (ic *InviteCreate) sqlSave(ctx context.Context) (*Invite, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *InviteCreate) createSpec() (*Invite, *sqlgraph.CreateSpec) {
	var (
		_node = &Invite{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(invite.Table, sqlgraph.NewFieldSpec(invite.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = ic.conflict
	if value, ok := ic.mutation.Code(); ok {
		_spec.SetField(invite.FieldCode, field.TypeUUID, value)
		_node.Code = value
	}
	if value, ok := ic.mutation.Email(); ok {
		_spec.SetField(invite.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := ic.mutation.UserID(); ok {
		_spec.SetField(invite.FieldUserID, field.TypeInt64, value)
		_node.UserID = &value
	}
	if value, ok := ic.mutation.Status(); ok {
		_spec.SetField(invite.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := ic.mutation.CreatedAt(); ok {
		_spec.SetField(invite.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ic.mutation.UpdatedAt(); ok {
		_spec.SetField(invite.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ic.mutation.RoleID(); ok {
		_spec.SetField(invite.FieldRoleID, field.TypeInt64, value)
		_node.RoleID = value
	}
	if value, ok := ic.mutation.Resource(); ok {
		_spec.SetField(invite.FieldResource, field.TypeString, value)
		_node.Resource = value
	}
	if value, ok := ic.mutation.ResourceID(); ok {
		_spec.SetField(invite.FieldResourceID, field.TypeInt64, value)
		_node.ResourceID = value
	}
	if nodes := ic.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invite.TenantTable,
			Columns: []string{invite.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invite.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InviteUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (ic *InviteCreate) OnConflict(opts ...sql.ConflictOption) *InviteUpsertOne {
	ic.conflict = opts
	return &InviteUpsertOne{
		create: ic,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invite.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ic *InviteCreate) OnConflictColumns(columns ...string) *InviteUpsertOne {
	ic.conflict = append(ic.conflict, sql.ConflictColumns(columns...))
	return &InviteUpsertOne{
		create: ic,
	}
}

type (
	// InviteUpsertOne is the builder for "upsert"-ing
	//  one Invite node.
	InviteUpsertOne struct {
		create *InviteCreate
	}

	// InviteUpsert is the "OnConflict" setter.
	InviteUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *InviteUpsert) SetUserID(v int64) *InviteUpsert {
	u.Set(invite.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InviteUpsert) UpdateUserID() *InviteUpsert {
	u.SetExcluded(invite.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *InviteUpsert) AddUserID(v int64) *InviteUpsert {
	u.Add(invite.FieldUserID, v)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *InviteUpsert) ClearUserID() *InviteUpsert {
	u.SetNull(invite.FieldUserID)
	return u
}

// SetStatus sets the "status" field.
func (u *InviteUpsert) SetStatus(v enum.InviteStatus) *InviteUpsert {
	u.Set(invite.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InviteUpsert) UpdateStatus() *InviteUpsert {
	u.SetExcluded(invite.FieldStatus)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InviteUpsert) SetUpdatedAt(v time.Time) *InviteUpsert {
	u.Set(invite.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InviteUpsert) UpdateUpdatedAt() *InviteUpsert {
	u.SetExcluded(invite.FieldUpdatedAt)
	return u
}

// SetRoleID sets the "role_id" field.
func (u *InviteUpsert) SetRoleID(v int64) *InviteUpsert {
	u.Set(invite.FieldRoleID, v)
	return u
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *InviteUpsert) UpdateRoleID() *InviteUpsert {
	u.SetExcluded(invite.FieldRoleID)
	return u
}

// AddRoleID adds v to the "role_id" field.
func (u *InviteUpsert) AddRoleID(v int64) *InviteUpsert {
	u.Add(invite.FieldRoleID, v)
	return u
}

// ClearRoleID clears the value of the "role_id" field.
func (u *InviteUpsert) ClearRoleID() *InviteUpsert {
	u.SetNull(invite.FieldRoleID)
	return u
}

// SetResource sets the "resource" field.
func (u *InviteUpsert) SetResource(v string) *InviteUpsert {
	u.Set(invite.FieldResource, v)
	return u
}

// UpdateResource sets the "resource" field to the value that was provided on create.
func (u *InviteUpsert) UpdateResource() *InviteUpsert {
	u.SetExcluded(invite.FieldResource)
	return u
}

// ClearResource clears the value of the "resource" field.
func (u *InviteUpsert) ClearResource() *InviteUpsert {
	u.SetNull(invite.FieldResource)
	return u
}

// SetResourceID sets the "resource_id" field.
func (u *InviteUpsert) SetResourceID(v int64) *InviteUpsert {
	u.Set(invite.FieldResourceID, v)
	return u
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *InviteUpsert) UpdateResourceID() *InviteUpsert {
	u.SetExcluded(invite.FieldResourceID)
	return u
}

// AddResourceID adds v to the "resource_id" field.
func (u *InviteUpsert) AddResourceID(v int64) *InviteUpsert {
	u.Add(invite.FieldResourceID, v)
	return u
}

// ClearResourceID clears the value of the "resource_id" field.
func (u *InviteUpsert) ClearResourceID() *InviteUpsert {
	u.SetNull(invite.FieldResourceID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Invite.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InviteUpsertOne) UpdateNewValues() *InviteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(invite.FieldTenantID)
		}
		if _, exists := u.create.mutation.Code(); exists {
			s.SetIgnore(invite.FieldCode)
		}
		if _, exists := u.create.mutation.Email(); exists {
			s.SetIgnore(invite.FieldEmail)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invite.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invite.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InviteUpsertOne) Ignore() *InviteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InviteUpsertOne) DoNothing() *InviteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InviteCreate.OnConflict
// documentation for more info.
func (u *InviteUpsertOne) Update(set func(*InviteUpsert)) *InviteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InviteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InviteUpsertOne) SetUserID(v int64) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *InviteUpsertOne) AddUserID(v int64) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateUserID() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *InviteUpsertOne) ClearUserID() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.ClearUserID()
	})
}

// SetStatus sets the "status" field.
func (u *InviteUpsertOne) SetStatus(v enum.InviteStatus) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateStatus() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InviteUpsertOne) SetUpdatedAt(v time.Time) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateUpdatedAt() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRoleID sets the "role_id" field.
func (u *InviteUpsertOne) SetRoleID(v int64) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetRoleID(v)
	})
}

// AddRoleID adds v to the "role_id" field.
func (u *InviteUpsertOne) AddRoleID(v int64) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.AddRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateRoleID() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateRoleID()
	})
}

// ClearRoleID clears the value of the "role_id" field.
func (u *InviteUpsertOne) ClearRoleID() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.ClearRoleID()
	})
}

// SetResource sets the "resource" field.
func (u *InviteUpsertOne) SetResource(v string) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetResource(v)
	})
}

// UpdateResource sets the "resource" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateResource() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateResource()
	})
}

// ClearResource clears the value of the "resource" field.
func (u *InviteUpsertOne) ClearResource() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.ClearResource()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *InviteUpsertOne) SetResourceID(v int64) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.SetResourceID(v)
	})
}

// AddResourceID adds v to the "resource_id" field.
func (u *InviteUpsertOne) AddResourceID(v int64) *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.AddResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *InviteUpsertOne) UpdateResourceID() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateResourceID()
	})
}

// ClearResourceID clears the value of the "resource_id" field.
func (u *InviteUpsertOne) ClearResourceID() *InviteUpsertOne {
	return u.Update(func(s *InviteUpsert) {
		s.ClearResourceID()
	})
}

// Exec executes the query.
func (u *InviteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InviteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InviteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InviteUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InviteUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InviteCreateBulk is the builder for creating many Invite entities in bulk.
type InviteCreateBulk struct {
	config
	err      error
	builders []*InviteCreate
	conflict []sql.ConflictOption
}

// Save creates the Invite entities in the database.
func (icb *InviteCreateBulk) Save(ctx context.Context) ([]*Invite, error) {
	if icb.err != nil {
		return nil, icb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Invite, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InviteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = icb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *InviteCreateBulk) SaveX(ctx context.Context) []*Invite {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *InviteCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *InviteCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invite.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InviteUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (icb *InviteCreateBulk) OnConflict(opts ...sql.ConflictOption) *InviteUpsertBulk {
	icb.conflict = opts
	return &InviteUpsertBulk{
		create: icb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invite.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (icb *InviteCreateBulk) OnConflictColumns(columns ...string) *InviteUpsertBulk {
	icb.conflict = append(icb.conflict, sql.ConflictColumns(columns...))
	return &InviteUpsertBulk{
		create: icb,
	}
}

// InviteUpsertBulk is the builder for "upsert"-ing
// a bulk of Invite nodes.
type InviteUpsertBulk struct {
	create *InviteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Invite.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InviteUpsertBulk) UpdateNewValues() *InviteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(invite.FieldTenantID)
			}
			if _, exists := b.mutation.Code(); exists {
				s.SetIgnore(invite.FieldCode)
			}
			if _, exists := b.mutation.Email(); exists {
				s.SetIgnore(invite.FieldEmail)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invite.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invite.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InviteUpsertBulk) Ignore() *InviteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InviteUpsertBulk) DoNothing() *InviteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InviteCreateBulk.OnConflict
// documentation for more info.
func (u *InviteUpsertBulk) Update(set func(*InviteUpsert)) *InviteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InviteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *InviteUpsertBulk) SetUserID(v int64) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *InviteUpsertBulk) AddUserID(v int64) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateUserID() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *InviteUpsertBulk) ClearUserID() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.ClearUserID()
	})
}

// SetStatus sets the "status" field.
func (u *InviteUpsertBulk) SetStatus(v enum.InviteStatus) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateStatus() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InviteUpsertBulk) SetUpdatedAt(v time.Time) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateUpdatedAt() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRoleID sets the "role_id" field.
func (u *InviteUpsertBulk) SetRoleID(v int64) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetRoleID(v)
	})
}

// AddRoleID adds v to the "role_id" field.
func (u *InviteUpsertBulk) AddRoleID(v int64) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.AddRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateRoleID() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateRoleID()
	})
}

// ClearRoleID clears the value of the "role_id" field.
func (u *InviteUpsertBulk) ClearRoleID() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.ClearRoleID()
	})
}

// SetResource sets the "resource" field.
func (u *InviteUpsertBulk) SetResource(v string) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetResource(v)
	})
}

// UpdateResource sets the "resource" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateResource() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateResource()
	})
}

// ClearResource clears the value of the "resource" field.
func (u *InviteUpsertBulk) ClearResource() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.ClearResource()
	})
}

// SetResourceID sets the "resource_id" field.
func (u *InviteUpsertBulk) SetResourceID(v int64) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.SetResourceID(v)
	})
}

// AddResourceID adds v to the "resource_id" field.
func (u *InviteUpsertBulk) AddResourceID(v int64) *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.AddResourceID(v)
	})
}

// UpdateResourceID sets the "resource_id" field to the value that was provided on create.
func (u *InviteUpsertBulk) UpdateResourceID() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.UpdateResourceID()
	})
}

// ClearResourceID clears the value of the "resource_id" field.
func (u *InviteUpsertBulk) ClearResourceID() *InviteUpsertBulk {
	return u.Update(func(s *InviteUpsert) {
		s.ClearResourceID()
	})
}

// Exec executes the query.
func (u *InviteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InviteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InviteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InviteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
