// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/tenants/ent/store"
	"gitlab.calendaria.team/services/tenants/ent/tenant"
)

// StoreCreate is the builder for creating a Store entity.
type StoreCreate struct {
	config
	mutation *StoreMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeletedAt sets the "deleted_at" field.
func (sc *StoreCreate) SetDeletedAt(t time.Time) *StoreCreate {
	sc.mutation.SetDeletedAt(t)
	return sc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sc *StoreCreate) SetNillableDeletedAt(t *time.Time) *StoreCreate {
	if t != nil {
		sc.SetDeletedAt(*t)
	}
	return sc
}

// SetTenantID sets the "tenant_id" field.
func (sc *StoreCreate) SetTenantID(i int64) *StoreCreate {
	sc.mutation.SetTenantID(i)
	return sc
}

// SetName sets the "name" field.
func (sc *StoreCreate) SetName(s string) *StoreCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetAddress sets the "address" field.
func (sc *StoreCreate) SetAddress(s string) *StoreCreate {
	sc.mutation.SetAddress(s)
	return sc
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (sc *StoreCreate) SetNillableAddress(s *string) *StoreCreate {
	if s != nil {
		sc.SetAddress(*s)
	}
	return sc
}

// SetLat sets the "lat" field.
func (sc *StoreCreate) SetLat(f float64) *StoreCreate {
	sc.mutation.SetLat(f)
	return sc
}

// SetNillableLat sets the "lat" field if the given value is not nil.
func (sc *StoreCreate) SetNillableLat(f *float64) *StoreCreate {
	if f != nil {
		sc.SetLat(*f)
	}
	return sc
}

// SetLon sets the "lon" field.
func (sc *StoreCreate) SetLon(f float64) *StoreCreate {
	sc.mutation.SetLon(f)
	return sc
}

// SetNillableLon sets the "lon" field if the given value is not nil.
func (sc *StoreCreate) SetNillableLon(f *float64) *StoreCreate {
	if f != nil {
		sc.SetLon(*f)
	}
	return sc
}

// SetPhone sets the "phone" field.
func (sc *StoreCreate) SetPhone(s string) *StoreCreate {
	sc.mutation.SetPhone(s)
	return sc
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (sc *StoreCreate) SetNillablePhone(s *string) *StoreCreate {
	if s != nil {
		sc.SetPhone(*s)
	}
	return sc
}

// SetWorkHours sets the "work_hours" field.
func (sc *StoreCreate) SetWorkHours(s string) *StoreCreate {
	sc.mutation.SetWorkHours(s)
	return sc
}

// SetNillableWorkHours sets the "work_hours" field if the given value is not nil.
func (sc *StoreCreate) SetNillableWorkHours(s *string) *StoreCreate {
	if s != nil {
		sc.SetWorkHours(*s)
	}
	return sc
}

// SetIsActive sets the "is_active" field.
func (sc *StoreCreate) SetIsActive(b bool) *StoreCreate {
	sc.mutation.SetIsActive(b)
	return sc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (sc *StoreCreate) SetNillableIsActive(b *bool) *StoreCreate {
	if b != nil {
		sc.SetIsActive(*b)
	}
	return sc
}

// SetResponsibleID sets the "responsible_id" field.
func (sc *StoreCreate) SetResponsibleID(i int64) *StoreCreate {
	sc.mutation.SetResponsibleID(i)
	return sc
}

// SetNillableResponsibleID sets the "responsible_id" field if the given value is not nil.
func (sc *StoreCreate) SetNillableResponsibleID(i *int64) *StoreCreate {
	if i != nil {
		sc.SetResponsibleID(*i)
	}
	return sc
}

// SetCreatedAt sets the "created_at" field.
func (sc *StoreCreate) SetCreatedAt(t time.Time) *StoreCreate {
	sc.mutation.SetCreatedAt(t)
	return sc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (sc *StoreCreate) SetNillableCreatedAt(t *time.Time) *StoreCreate {
	if t != nil {
		sc.SetCreatedAt(*t)
	}
	return sc
}

// SetUpdatedAt sets the "updated_at" field.
func (sc *StoreCreate) SetUpdatedAt(t time.Time) *StoreCreate {
	sc.mutation.SetUpdatedAt(t)
	return sc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (sc *StoreCreate) SetNillableUpdatedAt(t *time.Time) *StoreCreate {
	if t != nil {
		sc.SetUpdatedAt(*t)
	}
	return sc
}

// SetID sets the "id" field.
func (sc *StoreCreate) SetID(i int64) *StoreCreate {
	sc.mutation.SetID(i)
	return sc
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (sc *StoreCreate) SetTenant(t *Tenant) *StoreCreate {
	return sc.SetTenantID(t.ID)
}

// Mutation returns the StoreMutation object of the builder.
func (sc *StoreCreate) Mutation() *StoreMutation {
	return sc.mutation
}

// Save creates the Store in the database.
func (sc *StoreCreate) Save(ctx context.Context) (*Store, error) {
	if err := sc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *StoreCreate) SaveX(ctx context.Context) *Store {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *StoreCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *StoreCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *StoreCreate) defaults() error {
	if _, ok := sc.mutation.Address(); !ok {
		v := store.DefaultAddress
		sc.mutation.SetAddress(v)
	}
	if _, ok := sc.mutation.Phone(); !ok {
		v := store.DefaultPhone
		sc.mutation.SetPhone(v)
	}
	if _, ok := sc.mutation.WorkHours(); !ok {
		v := store.DefaultWorkHours
		sc.mutation.SetWorkHours(v)
	}
	if _, ok := sc.mutation.IsActive(); !ok {
		v := store.DefaultIsActive
		sc.mutation.SetIsActive(v)
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		if store.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized store.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := store.DefaultCreatedAt()
		sc.mutation.SetCreatedAt(v)
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		if store.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized store.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := store.DefaultUpdatedAt()
		sc.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (sc *StoreCreate) check() error {
	if _, ok := sc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Store.tenant_id"`)}
	}
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Store.name"`)}
	}
	if v, ok := sc.mutation.Name(); ok {
		if err := store.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Store.name": %w`, err)}
		}
	}
	if _, ok := sc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Store.is_active"`)}
	}
	if _, ok := sc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Store.created_at"`)}
	}
	if _, ok := sc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Store.updated_at"`)}
	}
	if len(sc.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Store.tenant"`)}
	}
	return nil
}

func (sc *StoreCreate) sqlSave(ctx context.Context) (*Store, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *StoreCreate) createSpec() (*Store, *sqlgraph.CreateSpec) {
	var (
		_node = &Store{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(store.Table, sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = sc.conflict
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.DeletedAt(); ok {
		_spec.SetField(store.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(store.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.Address(); ok {
		_spec.SetField(store.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := sc.mutation.Lat(); ok {
		_spec.SetField(store.FieldLat, field.TypeFloat64, value)
		_node.Lat = &value
	}
	if value, ok := sc.mutation.Lon(); ok {
		_spec.SetField(store.FieldLon, field.TypeFloat64, value)
		_node.Lon = &value
	}
	if value, ok := sc.mutation.Phone(); ok {
		_spec.SetField(store.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := sc.mutation.WorkHours(); ok {
		_spec.SetField(store.FieldWorkHours, field.TypeString, value)
		_node.WorkHours = value
	}
	if value, ok := sc.mutation.IsActive(); ok {
		_spec.SetField(store.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := sc.mutation.ResponsibleID(); ok {
		_spec.SetField(store.FieldResponsibleID, field.TypeInt64, value)
		_node.ResponsibleID = &value
	}
	if value, ok := sc.mutation.CreatedAt(); ok {
		_spec.SetField(store.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := sc.mutation.UpdatedAt(); ok {
		_spec.SetField(store.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := sc.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   store.TenantTable,
			Columns: []string{store.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Store.Create().
//		SetDeletedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StoreUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (sc *StoreCreate) OnConflict(opts ...sql.ConflictOption) *StoreUpsertOne {
	sc.conflict = opts
	return &StoreUpsertOne{
		create: sc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Store.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (sc *StoreCreate) OnConflictColumns(columns ...string) *StoreUpsertOne {
	sc.conflict = append(sc.conflict, sql.ConflictColumns(columns...))
	return &StoreUpsertOne{
		create: sc,
	}
}

type (
	// StoreUpsertOne is the builder for "upsert"-ing
	//  one Store node.
	StoreUpsertOne struct {
		create *StoreCreate
	}

	// StoreUpsert is the "OnConflict" setter.
	StoreUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeletedAt sets the "deleted_at" field.
func (u *StoreUpsert) SetDeletedAt(v time.Time) *StoreUpsert {
	u.Set(store.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *StoreUpsert) UpdateDeletedAt() *StoreUpsert {
	u.SetExcluded(store.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *StoreUpsert) ClearDeletedAt() *StoreUpsert {
	u.SetNull(store.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *StoreUpsert) SetName(v string) *StoreUpsert {
	u.Set(store.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *StoreUpsert) UpdateName() *StoreUpsert {
	u.SetExcluded(store.FieldName)
	return u
}

// SetAddress sets the "address" field.
func (u *StoreUpsert) SetAddress(v string) *StoreUpsert {
	u.Set(store.FieldAddress, v)
	return u
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *StoreUpsert) UpdateAddress() *StoreUpsert {
	u.SetExcluded(store.FieldAddress)
	return u
}

// ClearAddress clears the value of the "address" field.
func (u *StoreUpsert) ClearAddress() *StoreUpsert {
	u.SetNull(store.FieldAddress)
	return u
}

// SetLat sets the "lat" field.
func (u *StoreUpsert) SetLat(v float64) *StoreUpsert {
	u.Set(store.FieldLat, v)
	return u
}

// UpdateLat sets the "lat" field to the value that was provided on create.
func (u *StoreUpsert) UpdateLat() *StoreUpsert {
	u.SetExcluded(store.FieldLat)
	return u
}

// AddLat adds v to the "lat" field.
func (u *StoreUpsert) AddLat(v float64) *StoreUpsert {
	u.Add(store.FieldLat, v)
	return u
}

// ClearLat clears the value of the "lat" field.
func (u *StoreUpsert) ClearLat() *StoreUpsert {
	u.SetNull(store.FieldLat)
	return u
}

// SetLon sets the "lon" field.
func (u *StoreUpsert) SetLon(v float64) *StoreUpsert {
	u.Set(store.FieldLon, v)
	return u
}

// UpdateLon sets the "lon" field to the value that was provided on create.
func (u *StoreUpsert) UpdateLon() *StoreUpsert {
	u.SetExcluded(store.FieldLon)
	return u
}

// AddLon adds v to the "lon" field.
func (u *StoreUpsert) AddLon(v float64) *StoreUpsert {
	u.Add(store.FieldLon, v)
	return u
}

// ClearLon clears the value of the "lon" field.
func (u *StoreUpsert) ClearLon() *StoreUpsert {
	u.SetNull(store.FieldLon)
	return u
}

// SetPhone sets the "phone" field.
func (u *StoreUpsert) SetPhone(v string) *StoreUpsert {
	u.Set(store.FieldPhone, v)
	return u
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *StoreUpsert) UpdatePhone() *StoreUpsert {
	u.SetExcluded(store.FieldPhone)
	return u
}

// ClearPhone clears the value of the "phone" field.
func (u *StoreUpsert) ClearPhone() *StoreUpsert {
	u.SetNull(store.FieldPhone)
	return u
}

// SetWorkHours sets the "work_hours" field.
func (u *StoreUpsert) SetWorkHours(v string) *StoreUpsert {
	u.Set(store.FieldWorkHours, v)
	return u
}

// UpdateWorkHours sets the "work_hours" field to the value that was provided on create.
func (u *StoreUpsert) UpdateWorkHours() *StoreUpsert {
	u.SetExcluded(store.FieldWorkHours)
	return u
}

// ClearWorkHours clears the value of the "work_hours" field.
func (u *StoreUpsert) ClearWorkHours() *StoreUpsert {
	u.SetNull(store.FieldWorkHours)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *StoreUpsert) SetIsActive(v bool) *StoreUpsert {
	u.Set(store.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *StoreUpsert) UpdateIsActive() *StoreUpsert {
	u.SetExcluded(store.FieldIsActive)
	return u
}

// SetResponsibleID sets the "responsible_id" field.
func (u *StoreUpsert) SetResponsibleID(v int64) *StoreUpsert {
	u.Set(store.FieldResponsibleID, v)
	return u
}

// UpdateResponsibleID sets the "responsible_id" field to the value that was provided on create.
func (u *StoreUpsert) UpdateResponsibleID() *StoreUpsert {
	u.SetExcluded(store.FieldResponsibleID)
	return u
}

// AddResponsibleID adds v to the "responsible_id" field.
func (u *StoreUpsert) AddResponsibleID(v int64) *StoreUpsert {
	u.Add(store.FieldResponsibleID, v)
	return u
}

// ClearResponsibleID clears the value of the "responsible_id" field.
func (u *StoreUpsert) ClearResponsibleID() *StoreUpsert {
	u.SetNull(store.FieldResponsibleID)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StoreUpsert) SetUpdatedAt(v time.Time) *StoreUpsert {
	u.Set(store.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StoreUpsert) UpdateUpdatedAt() *StoreUpsert {
	u.SetExcluded(store.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Store.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(store.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StoreUpsertOne) UpdateNewValues() *StoreUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(store.FieldID)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(store.FieldTenantID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(store.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Store.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *StoreUpsertOne) Ignore() *StoreUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StoreUpsertOne) DoNothing() *StoreUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StoreCreate.OnConflict
// documentation for more info.
func (u *StoreUpsertOne) Update(set func(*StoreUpsert)) *StoreUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StoreUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *StoreUpsertOne) SetDeletedAt(v time.Time) *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *StoreUpsertOne) UpdateDeletedAt() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *StoreUpsertOne) ClearDeletedAt() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *StoreUpsertOne) SetName(v string) *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *StoreUpsertOne) UpdateName() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateName()
	})
}

// SetAddress sets the "address" field.
func (u *StoreUpsertOne) SetAddress(v string) *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *StoreUpsertOne) UpdateAddress() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateAddress()
	})
}

// ClearAddress clears the value of the "address" field.
func (u *StoreUpsertOne) ClearAddress() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.ClearAddress()
	})
}

// SetLat sets the "lat" field.
func (u *StoreUpsertOne) SetLat(v float64) *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.SetLat(v)
	})
}

// AddLat adds v to the "lat" field.
func (u *StoreUpsertOne) AddLat(v float64) *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.AddLat(v)
	})
}

// UpdateLat sets the "lat" field to the value that was provided on create.
func (u *StoreUpsertOne) UpdateLat() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateLat()
	})
}

// ClearLat clears the value of the "lat" field.
func (u *StoreUpsertOne) ClearLat() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.ClearLat()
	})
}

// SetLon sets the "lon" field.
func (u *StoreUpsertOne) SetLon(v float64) *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.SetLon(v)
	})
}

// AddLon adds v to the "lon" field.
func (u *StoreUpsertOne) AddLon(v float64) *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.AddLon(v)
	})
}

// UpdateLon sets the "lon" field to the value that was provided on create.
func (u *StoreUpsertOne) UpdateLon() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateLon()
	})
}

// ClearLon clears the value of the "lon" field.
func (u *StoreUpsertOne) ClearLon() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.ClearLon()
	})
}

// SetPhone sets the "phone" field.
func (u *StoreUpsertOne) SetPhone(v string) *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *StoreUpsertOne) UpdatePhone() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.UpdatePhone()
	})
}

// ClearPhone clears the value of the "phone" field.
func (u *StoreUpsertOne) ClearPhone() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.ClearPhone()
	})
}

// SetWorkHours sets the "work_hours" field.
func (u *StoreUpsertOne) SetWorkHours(v string) *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.SetWorkHours(v)
	})
}

// UpdateWorkHours sets the "work_hours" field to the value that was provided on create.
func (u *StoreUpsertOne) UpdateWorkHours() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateWorkHours()
	})
}

// ClearWorkHours clears the value of the "work_hours" field.
func (u *StoreUpsertOne) ClearWorkHours() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.ClearWorkHours()
	})
}

// SetIsActive sets the "is_active" field.
func (u *StoreUpsertOne) SetIsActive(v bool) *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *StoreUpsertOne) UpdateIsActive() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateIsActive()
	})
}

// SetResponsibleID sets the "responsible_id" field.
func (u *StoreUpsertOne) SetResponsibleID(v int64) *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.SetResponsibleID(v)
	})
}

// AddResponsibleID adds v to the "responsible_id" field.
func (u *StoreUpsertOne) AddResponsibleID(v int64) *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.AddResponsibleID(v)
	})
}

// UpdateResponsibleID sets the "responsible_id" field to the value that was provided on create.
func (u *StoreUpsertOne) UpdateResponsibleID() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateResponsibleID()
	})
}

// ClearResponsibleID clears the value of the "responsible_id" field.
func (u *StoreUpsertOne) ClearResponsibleID() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.ClearResponsibleID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StoreUpsertOne) SetUpdatedAt(v time.Time) *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StoreUpsertOne) UpdateUpdatedAt() *StoreUpsertOne {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *StoreUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StoreCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StoreUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *StoreUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *StoreUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// StoreCreateBulk is the builder for creating many Store entities in bulk.
type StoreCreateBulk struct {
	config
	err      error
	builders []*StoreCreate
	conflict []sql.ConflictOption
}

// Save creates the Store entities in the database.
func (scb *StoreCreateBulk) Save(ctx context.Context) ([]*Store, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Store, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StoreMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = scb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *StoreCreateBulk) SaveX(ctx context.Context) []*Store {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *StoreCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *StoreCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Store.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StoreUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (scb *StoreCreateBulk) OnConflict(opts ...sql.ConflictOption) *StoreUpsertBulk {
	scb.conflict = opts
	return &StoreUpsertBulk{
		create: scb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Store.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (scb *StoreCreateBulk) OnConflictColumns(columns ...string) *StoreUpsertBulk {
	scb.conflict = append(scb.conflict, sql.ConflictColumns(columns...))
	return &StoreUpsertBulk{
		create: scb,
	}
}

// StoreUpsertBulk is the builder for "upsert"-ing
// a bulk of Store nodes.
type StoreUpsertBulk struct {
	create *StoreCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Store.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(store.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StoreUpsertBulk) UpdateNewValues() *StoreUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(store.FieldID)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(store.FieldTenantID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(store.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Store.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *StoreUpsertBulk) Ignore() *StoreUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StoreUpsertBulk) DoNothing() *StoreUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StoreCreateBulk.OnConflict
// documentation for more info.
func (u *StoreUpsertBulk) Update(set func(*StoreUpsert)) *StoreUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StoreUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *StoreUpsertBulk) SetDeletedAt(v time.Time) *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *StoreUpsertBulk) UpdateDeletedAt() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *StoreUpsertBulk) ClearDeletedAt() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *StoreUpsertBulk) SetName(v string) *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *StoreUpsertBulk) UpdateName() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateName()
	})
}

// SetAddress sets the "address" field.
func (u *StoreUpsertBulk) SetAddress(v string) *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.SetAddress(v)
	})
}

// UpdateAddress sets the "address" field to the value that was provided on create.
func (u *StoreUpsertBulk) UpdateAddress() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateAddress()
	})
}

// ClearAddress clears the value of the "address" field.
func (u *StoreUpsertBulk) ClearAddress() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.ClearAddress()
	})
}

// SetLat sets the "lat" field.
func (u *StoreUpsertBulk) SetLat(v float64) *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.SetLat(v)
	})
}

// AddLat adds v to the "lat" field.
func (u *StoreUpsertBulk) AddLat(v float64) *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.AddLat(v)
	})
}

// UpdateLat sets the "lat" field to the value that was provided on create.
func (u *StoreUpsertBulk) UpdateLat() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateLat()
	})
}

// ClearLat clears the value of the "lat" field.
func (u *StoreUpsertBulk) ClearLat() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.ClearLat()
	})
}

// SetLon sets the "lon" field.
func (u *StoreUpsertBulk) SetLon(v float64) *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.SetLon(v)
	})
}

// AddLon adds v to the "lon" field.
func (u *StoreUpsertBulk) AddLon(v float64) *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.AddLon(v)
	})
}

// UpdateLon sets the "lon" field to the value that was provided on create.
func (u *StoreUpsertBulk) UpdateLon() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateLon()
	})
}

// ClearLon clears the value of the "lon" field.
func (u *StoreUpsertBulk) ClearLon() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.ClearLon()
	})
}

// SetPhone sets the "phone" field.
func (u *StoreUpsertBulk) SetPhone(v string) *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *StoreUpsertBulk) UpdatePhone() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.UpdatePhone()
	})
}

// ClearPhone clears the value of the "phone" field.
func (u *StoreUpsertBulk) ClearPhone() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.ClearPhone()
	})
}

// SetWorkHours sets the "work_hours" field.
func (u *StoreUpsertBulk) SetWorkHours(v string) *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.SetWorkHours(v)
	})
}

// UpdateWorkHours sets the "work_hours" field to the value that was provided on create.
func (u *StoreUpsertBulk) UpdateWorkHours() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateWorkHours()
	})
}

// ClearWorkHours clears the value of the "work_hours" field.
func (u *StoreUpsertBulk) ClearWorkHours() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.ClearWorkHours()
	})
}

// SetIsActive sets the "is_active" field.
func (u *StoreUpsertBulk) SetIsActive(v bool) *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *StoreUpsertBulk) UpdateIsActive() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateIsActive()
	})
}

// SetResponsibleID sets the "responsible_id" field.
func (u *StoreUpsertBulk) SetResponsibleID(v int64) *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.SetResponsibleID(v)
	})
}

// AddResponsibleID adds v to the "responsible_id" field.
func (u *StoreUpsertBulk) AddResponsibleID(v int64) *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.AddResponsibleID(v)
	})
}

// UpdateResponsibleID sets the "responsible_id" field to the value that was provided on create.
func (u *StoreUpsertBulk) UpdateResponsibleID() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateResponsibleID()
	})
}

// ClearResponsibleID clears the value of the "responsible_id" field.
func (u *StoreUpsertBulk) ClearResponsibleID() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.ClearResponsibleID()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StoreUpsertBulk) SetUpdatedAt(v time.Time) *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StoreUpsertBulk) UpdateUpdatedAt() *StoreUpsertBulk {
	return u.Update(func(s *StoreUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *StoreUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the StoreCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StoreCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StoreUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
