// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/tenants/ent/predicate"
	"gitlab.calendaria.team/services/tenants/ent/store"
)

// StoreUpdate is the builder for updating Store entities.
type StoreUpdate struct {
	config
	hooks     []Hook
	mutation  *StoreMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the StoreUpdate builder.
func (su *StoreUpdate) Where(ps ...predicate.Store) *StoreUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetDeletedAt sets the "deleted_at" field.
func (su *StoreUpdate) SetDeletedAt(t time.Time) *StoreUpdate {
	su.mutation.SetDeletedAt(t)
	return su
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (su *StoreUpdate) SetNillableDeletedAt(t *time.Time) *StoreUpdate {
	if t != nil {
		su.SetDeletedAt(*t)
	}
	return su
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (su *StoreUpdate) ClearDeletedAt() *StoreUpdate {
	su.mutation.ClearDeletedAt()
	return su
}

// SetName sets the "name" field.
func (su *StoreUpdate) SetName(s string) *StoreUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *StoreUpdate) SetNillableName(s *string) *StoreUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetAddress sets the "address" field.
func (su *StoreUpdate) SetAddress(s string) *StoreUpdate {
	su.mutation.SetAddress(s)
	return su
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (su *StoreUpdate) SetNillableAddress(s *string) *StoreUpdate {
	if s != nil {
		su.SetAddress(*s)
	}
	return su
}

// ClearAddress clears the value of the "address" field.
func (su *StoreUpdate) ClearAddress() *StoreUpdate {
	su.mutation.ClearAddress()
	return su
}

// SetLat sets the "lat" field.
func (su *StoreUpdate) SetLat(f float64) *StoreUpdate {
	su.mutation.ResetLat()
	su.mutation.SetLat(f)
	return su
}

// SetNillableLat sets the "lat" field if the given value is not nil.
func (su *StoreUpdate) SetNillableLat(f *float64) *StoreUpdate {
	if f != nil {
		su.SetLat(*f)
	}
	return su
}

// AddLat adds f to the "lat" field.
func (su *StoreUpdate) AddLat(f float64) *StoreUpdate {
	su.mutation.AddLat(f)
	return su
}

// ClearLat clears the value of the "lat" field.
func (su *StoreUpdate) ClearLat() *StoreUpdate {
	su.mutation.ClearLat()
	return su
}

// SetLon sets the "lon" field.
func (su *StoreUpdate) SetLon(f float64) *StoreUpdate {
	su.mutation.ResetLon()
	su.mutation.SetLon(f)
	return su
}

// SetNillableLon sets the "lon" field if the given value is not nil.
func (su *StoreUpdate) SetNillableLon(f *float64) *StoreUpdate {
	if f != nil {
		su.SetLon(*f)
	}
	return su
}

// AddLon adds f to the "lon" field.
func (su *StoreUpdate) AddLon(f float64) *StoreUpdate {
	su.mutation.AddLon(f)
	return su
}

// ClearLon clears the value of the "lon" field.
func (su *StoreUpdate) ClearLon() *StoreUpdate {
	su.mutation.ClearLon()
	return su
}

// SetPhone sets the "phone" field.
func (su *StoreUpdate) SetPhone(s string) *StoreUpdate {
	su.mutation.SetPhone(s)
	return su
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (su *StoreUpdate) SetNillablePhone(s *string) *StoreUpdate {
	if s != nil {
		su.SetPhone(*s)
	}
	return su
}

// ClearPhone clears the value of the "phone" field.
func (su *StoreUpdate) ClearPhone() *StoreUpdate {
	su.mutation.ClearPhone()
	return su
}

// SetWorkHours sets the "work_hours" field.
func (su *StoreUpdate) SetWorkHours(s string) *StoreUpdate {
	su.mutation.SetWorkHours(s)
	return su
}

// SetNillableWorkHours sets the "work_hours" field if the given value is not nil.
func (su *StoreUpdate) SetNillableWorkHours(s *string) *StoreUpdate {
	if s != nil {
		su.SetWorkHours(*s)
	}
	return su
}

// ClearWorkHours clears the value of the "work_hours" field.
func (su *StoreUpdate) ClearWorkHours() *StoreUpdate {
	su.mutation.ClearWorkHours()
	return su
}

// SetIsActive sets the "is_active" field.
func (su *StoreUpdate) SetIsActive(b bool) *StoreUpdate {
	su.mutation.SetIsActive(b)
	return su
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (su *StoreUpdate) SetNillableIsActive(b *bool) *StoreUpdate {
	if b != nil {
		su.SetIsActive(*b)
	}
	return su
}

// SetResponsibleID sets the "responsible_id" field.
func (su *StoreUpdate) SetResponsibleID(i int64) *StoreUpdate {
	su.mutation.ResetResponsibleID()
	su.mutation.SetResponsibleID(i)
	return su
}

// SetNillableResponsibleID sets the "responsible_id" field if the given value is not nil.
func (su *StoreUpdate) SetNillableResponsibleID(i *int64) *StoreUpdate {
	if i != nil {
		su.SetResponsibleID(*i)
	}
	return su
}

// AddResponsibleID adds i to the "responsible_id" field.
func (su *StoreUpdate) AddResponsibleID(i int64) *StoreUpdate {
	su.mutation.AddResponsibleID(i)
	return su
}

// ClearResponsibleID clears the value of the "responsible_id" field.
func (su *StoreUpdate) ClearResponsibleID() *StoreUpdate {
	su.mutation.ClearResponsibleID()
	return su
}

// SetUpdatedAt sets the "updated_at" field.
func (su *StoreUpdate) SetUpdatedAt(t time.Time) *StoreUpdate {
	su.mutation.SetUpdatedAt(t)
	return su
}

// Mutation returns the StoreMutation object of the builder.
func (su *StoreUpdate) Mutation() *StoreMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *StoreUpdate) Save(ctx context.Context) (int, error) {
	if err := su.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *StoreUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *StoreUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *StoreUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (su *StoreUpdate) defaults() error {
	if _, ok := su.mutation.UpdatedAt(); !ok {
		if store.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized store.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := store.UpdateDefaultUpdatedAt()
		su.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (su *StoreUpdate) check() error {
	if v, ok := su.mutation.Name(); ok {
		if err := store.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Store.name": %w`, err)}
		}
	}
	if su.mutation.TenantCleared() && len(su.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Store.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (su *StoreUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *StoreUpdate {
	su.modifiers = append(su.modifiers, modifiers...)
	return su
}

func (su *StoreUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(store.Table, store.Columns, sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt64))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.DeletedAt(); ok {
		_spec.SetField(store.FieldDeletedAt, field.TypeTime, value)
	}
	if su.mutation.DeletedAtCleared() {
		_spec.ClearField(store.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(store.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.Address(); ok {
		_spec.SetField(store.FieldAddress, field.TypeString, value)
	}
	if su.mutation.AddressCleared() {
		_spec.ClearField(store.FieldAddress, field.TypeString)
	}
	if value, ok := su.mutation.Lat(); ok {
		_spec.SetField(store.FieldLat, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedLat(); ok {
		_spec.AddField(store.FieldLat, field.TypeFloat64, value)
	}
	if su.mutation.LatCleared() {
		_spec.ClearField(store.FieldLat, field.TypeFloat64)
	}
	if value, ok := su.mutation.Lon(); ok {
		_spec.SetField(store.FieldLon, field.TypeFloat64, value)
	}
	if value, ok := su.mutation.AddedLon(); ok {
		_spec.AddField(store.FieldLon, field.TypeFloat64, value)
	}
	if su.mutation.LonCleared() {
		_spec.ClearField(store.FieldLon, field.TypeFloat64)
	}
	if value, ok := su.mutation.Phone(); ok {
		_spec.SetField(store.FieldPhone, field.TypeString, value)
	}
	if su.mutation.PhoneCleared() {
		_spec.ClearField(store.FieldPhone, field.TypeString)
	}
	if value, ok := su.mutation.WorkHours(); ok {
		_spec.SetField(store.FieldWorkHours, field.TypeString, value)
	}
	if su.mutation.WorkHoursCleared() {
		_spec.ClearField(store.FieldWorkHours, field.TypeString)
	}
	if value, ok := su.mutation.IsActive(); ok {
		_spec.SetField(store.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := su.mutation.ResponsibleID(); ok {
		_spec.SetField(store.FieldResponsibleID, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedResponsibleID(); ok {
		_spec.AddField(store.FieldResponsibleID, field.TypeInt64, value)
	}
	if su.mutation.ResponsibleIDCleared() {
		_spec.ClearField(store.FieldResponsibleID, field.TypeInt64)
	}
	if value, ok := su.mutation.UpdatedAt(); ok {
		_spec.SetField(store.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(su.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{store.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// StoreUpdateOne is the builder for updating a single Store entity.
type StoreUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *StoreMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDeletedAt sets the "deleted_at" field.
func (suo *StoreUpdateOne) SetDeletedAt(t time.Time) *StoreUpdateOne {
	suo.mutation.SetDeletedAt(t)
	return suo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (suo *StoreUpdateOne) SetNillableDeletedAt(t *time.Time) *StoreUpdateOne {
	if t != nil {
		suo.SetDeletedAt(*t)
	}
	return suo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (suo *StoreUpdateOne) ClearDeletedAt() *StoreUpdateOne {
	suo.mutation.ClearDeletedAt()
	return suo
}

// SetName sets the "name" field.
func (suo *StoreUpdateOne) SetName(s string) *StoreUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *StoreUpdateOne) SetNillableName(s *string) *StoreUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetAddress sets the "address" field.
func (suo *StoreUpdateOne) SetAddress(s string) *StoreUpdateOne {
	suo.mutation.SetAddress(s)
	return suo
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (suo *StoreUpdateOne) SetNillableAddress(s *string) *StoreUpdateOne {
	if s != nil {
		suo.SetAddress(*s)
	}
	return suo
}

// ClearAddress clears the value of the "address" field.
func (suo *StoreUpdateOne) ClearAddress() *StoreUpdateOne {
	suo.mutation.ClearAddress()
	return suo
}

// SetLat sets the "lat" field.
func (suo *StoreUpdateOne) SetLat(f float64) *StoreUpdateOne {
	suo.mutation.ResetLat()
	suo.mutation.SetLat(f)
	return suo
}

// SetNillableLat sets the "lat" field if the given value is not nil.
func (suo *StoreUpdateOne) SetNillableLat(f *float64) *StoreUpdateOne {
	if f != nil {
		suo.SetLat(*f)
	}
	return suo
}

// AddLat adds f to the "lat" field.
func (suo *StoreUpdateOne) AddLat(f float64) *StoreUpdateOne {
	suo.mutation.AddLat(f)
	return suo
}

// ClearLat clears the value of the "lat" field.
func (suo *StoreUpdateOne) ClearLat() *StoreUpdateOne {
	suo.mutation.ClearLat()
	return suo
}

// SetLon sets the "lon" field.
func (suo *StoreUpdateOne) SetLon(f float64) *StoreUpdateOne {
	suo.mutation.ResetLon()
	suo.mutation.SetLon(f)
	return suo
}

// SetNillableLon sets the "lon" field if the given value is not nil.
func (suo *StoreUpdateOne) SetNillableLon(f *float64) *StoreUpdateOne {
	if f != nil {
		suo.SetLon(*f)
	}
	return suo
}

// AddLon adds f to the "lon" field.
func (suo *StoreUpdateOne) AddLon(f float64) *StoreUpdateOne {
	suo.mutation.AddLon(f)
	return suo
}

// ClearLon clears the value of the "lon" field.
func (suo *StoreUpdateOne) ClearLon() *StoreUpdateOne {
	suo.mutation.ClearLon()
	return suo
}

// SetPhone sets the "phone" field.
func (suo *StoreUpdateOne) SetPhone(s string) *StoreUpdateOne {
	suo.mutation.SetPhone(s)
	return suo
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (suo *StoreUpdateOne) SetNillablePhone(s *string) *StoreUpdateOne {
	if s != nil {
		suo.SetPhone(*s)
	}
	return suo
}

// ClearPhone clears the value of the "phone" field.
func (suo *StoreUpdateOne) ClearPhone() *StoreUpdateOne {
	suo.mutation.ClearPhone()
	return suo
}

// SetWorkHours sets the "work_hours" field.
func (suo *StoreUpdateOne) SetWorkHours(s string) *StoreUpdateOne {
	suo.mutation.SetWorkHours(s)
	return suo
}

// SetNillableWorkHours sets the "work_hours" field if the given value is not nil.
func (suo *StoreUpdateOne) SetNillableWorkHours(s *string) *StoreUpdateOne {
	if s != nil {
		suo.SetWorkHours(*s)
	}
	return suo
}

// ClearWorkHours clears the value of the "work_hours" field.
func (suo *StoreUpdateOne) ClearWorkHours() *StoreUpdateOne {
	suo.mutation.ClearWorkHours()
	return suo
}

// SetIsActive sets the "is_active" field.
func (suo *StoreUpdateOne) SetIsActive(b bool) *StoreUpdateOne {
	suo.mutation.SetIsActive(b)
	return suo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (suo *StoreUpdateOne) SetNillableIsActive(b *bool) *StoreUpdateOne {
	if b != nil {
		suo.SetIsActive(*b)
	}
	return suo
}

// SetResponsibleID sets the "responsible_id" field.
func (suo *StoreUpdateOne) SetResponsibleID(i int64) *StoreUpdateOne {
	suo.mutation.ResetResponsibleID()
	suo.mutation.SetResponsibleID(i)
	return suo
}

// SetNillableResponsibleID sets the "responsible_id" field if the given value is not nil.
func (suo *StoreUpdateOne) SetNillableResponsibleID(i *int64) *StoreUpdateOne {
	if i != nil {
		suo.SetResponsibleID(*i)
	}
	return suo
}

// AddResponsibleID adds i to the "responsible_id" field.
func (suo *StoreUpdateOne) AddResponsibleID(i int64) *StoreUpdateOne {
	suo.mutation.AddResponsibleID(i)
	return suo
}

// ClearResponsibleID clears the value of the "responsible_id" field.
func (suo *StoreUpdateOne) ClearResponsibleID() *StoreUpdateOne {
	suo.mutation.ClearResponsibleID()
	return suo
}

// SetUpdatedAt sets the "updated_at" field.
func (suo *StoreUpdateOne) SetUpdatedAt(t time.Time) *StoreUpdateOne {
	suo.mutation.SetUpdatedAt(t)
	return suo
}

// Mutation returns the StoreMutation object of the builder.
func (suo *StoreUpdateOne) Mutation() *StoreMutation {
	return suo.mutation
}

// Where appends a list predicates to the StoreUpdate builder.
func (suo *StoreUpdateOne) Where(ps ...predicate.Store) *StoreUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *StoreUpdateOne) Select(field string, fields ...string) *StoreUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Store entity.
func (suo *StoreUpdateOne) Save(ctx context.Context) (*Store, error) {
	if err := suo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *StoreUpdateOne) SaveX(ctx context.Context) *Store {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *StoreUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *StoreUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (suo *StoreUpdateOne) defaults() error {
	if _, ok := suo.mutation.UpdatedAt(); !ok {
		if store.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized store.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := store.UpdateDefaultUpdatedAt()
		suo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (suo *StoreUpdateOne) check() error {
	if v, ok := suo.mutation.Name(); ok {
		if err := store.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Store.name": %w`, err)}
		}
	}
	if suo.mutation.TenantCleared() && len(suo.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Store.tenant"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (suo *StoreUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *StoreUpdateOne {
	suo.modifiers = append(suo.modifiers, modifiers...)
	return suo
}

func (suo *StoreUpdateOne) sqlSave(ctx context.Context) (_node *Store, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(store.Table, store.Columns, sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt64))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Store.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, store.FieldID)
		for _, f := range fields {
			if !store.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != store.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.DeletedAt(); ok {
		_spec.SetField(store.FieldDeletedAt, field.TypeTime, value)
	}
	if suo.mutation.DeletedAtCleared() {
		_spec.ClearField(store.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(store.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.Address(); ok {
		_spec.SetField(store.FieldAddress, field.TypeString, value)
	}
	if suo.mutation.AddressCleared() {
		_spec.ClearField(store.FieldAddress, field.TypeString)
	}
	if value, ok := suo.mutation.Lat(); ok {
		_spec.SetField(store.FieldLat, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedLat(); ok {
		_spec.AddField(store.FieldLat, field.TypeFloat64, value)
	}
	if suo.mutation.LatCleared() {
		_spec.ClearField(store.FieldLat, field.TypeFloat64)
	}
	if value, ok := suo.mutation.Lon(); ok {
		_spec.SetField(store.FieldLon, field.TypeFloat64, value)
	}
	if value, ok := suo.mutation.AddedLon(); ok {
		_spec.AddField(store.FieldLon, field.TypeFloat64, value)
	}
	if suo.mutation.LonCleared() {
		_spec.ClearField(store.FieldLon, field.TypeFloat64)
	}
	if value, ok := suo.mutation.Phone(); ok {
		_spec.SetField(store.FieldPhone, field.TypeString, value)
	}
	if suo.mutation.PhoneCleared() {
		_spec.ClearField(store.FieldPhone, field.TypeString)
	}
	if value, ok := suo.mutation.WorkHours(); ok {
		_spec.SetField(store.FieldWorkHours, field.TypeString, value)
	}
	if suo.mutation.WorkHoursCleared() {
		_spec.ClearField(store.FieldWorkHours, field.TypeString)
	}
	if value, ok := suo.mutation.IsActive(); ok {
		_spec.SetField(store.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := suo.mutation.ResponsibleID(); ok {
		_spec.SetField(store.FieldResponsibleID, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedResponsibleID(); ok {
		_spec.AddField(store.FieldResponsibleID, field.TypeInt64, value)
	}
	if suo.mutation.ResponsibleIDCleared() {
		_spec.ClearField(store.FieldResponsibleID, field.TypeInt64)
	}
	if value, ok := suo.mutation.UpdatedAt(); ok {
		_spec.SetField(store.FieldUpdatedAt, field.TypeTime, value)
	}
	_spec.AddModifiers(suo.modifiers...)
	_node = &Store{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{store.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
