server:
  http:
    addr: 0.0.0.0:8000
    timeout: 30s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 30s
db: host=10.2.8.175 port=5432 user=tenants dbname=tenants password=oow6uya6aeX=oto
nats: nats://10.2.4.6:4222
discovery:
  iam: discovery:///iam
  iam_timeout: 30s
  rbac: discovery:///rbac
  rbac_timeout: 30s
