// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.calendaria.team/services/tenants/internal/biz"
	"gitlab.calendaria.team/services/tenants/internal/conf"
	"gitlab.calendaria.team/services/tenants/internal/data"
	"gitlab.calendaria.team/services/tenants/internal/server"
	"gitlab.calendaria.team/services/tenants/internal/service"
	"gitlab.calendaria.team/services/utils/v1/config"
	"gitlab.calendaria.team/services/utils/v1/dialer"
	"gitlab.calendaria.team/services/utils/v1/jwt"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	jwtProcessor, err := jwt.NewJwtProcessor(configConfig)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap, configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	tenantsRepo := data.NewTenantsRepo(dataData)
	dialerDialer, err := dialer.NewDialer(configConfig, jwtProcessor)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rbacRemote, err := data.NewRbacRemote(dialerDialer, bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tenantsUsecase, err := biz.NewTenantsUsecase(logger, tenantsRepo, rbacRemote)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	membersRepo := data.NewMembersRepo(dataData)
	iamRemote, err := data.NewIamRemote(dialerDialer, bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	membersUsecase, err := biz.NewMembersUsecase(logger, jwtProcessor, dialerDialer, tenantsRepo, membersRepo, iamRemote)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tenantsService := service.NewTenantsService(jwtProcessor, tenantsUsecase, membersUsecase)
	membersService := service.NewMembersService(jwtProcessor, tenantsUsecase, membersUsecase)
	invitesRepo := data.NewInvitesRepo(dataData)
	invitesUsecase, err := biz.NewInvitesUsecase(logger, jwtProcessor, tenantsRepo, invitesRepo, iamRemote)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	invitesService := service.NewInvitesService(jwtProcessor, tenantsUsecase, invitesUsecase)
	groupsRepo := data.NewGroupsRepo(dataData)
	groupsUsecase, err := biz.NewGroupsUsecase(logger, jwtProcessor, dialerDialer, tenantsRepo, groupsRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	groupsService := service.NewGroupsService(jwtProcessor, tenantsUsecase, groupsUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, logger, jwtProcessor, tenantsService, membersService, invitesService, groupsService)
	httpServer := server.NewHTTPServer(bootstrap, logger, jwtProcessor, tenantsService, membersService, invitesService, groupsService)
	app := newApp(logger, configConfig, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
