// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"teams/internal/biz"
	"teams/internal/conf"
	"teams/internal/data"
	"teams/internal/server"
	"teams/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	config, err := data.NewConfig(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	jwtProcessor, err := data.NewJwtProcessor(config)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	teamsRepo := data.NewTeamsRepo(dataData)
	teamsUsecase, err := biz.NewTeamsUsecase(logger, config, jwtProcessor, teamsRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dialer, err := data.NewDialer(config, jwtProcessor)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	membersRepo := data.NewMembersRepo(dataData)
	membersUsecase, err := biz.NewMembersUsecase(logger, jwtProcessor, dialer, teamsRepo, membersRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	teamsService := service.NewTeamsService(teamsUsecase, membersUsecase)
	membersService := service.NewMembersService(membersUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, logger, jwtProcessor, teamsService, membersService)
	httpServer := server.NewHTTPServer(bootstrap, logger, jwtProcessor, teamsService, membersService)
	app := newApp(logger, config, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
