// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.calendaria.team/services/tenants/internal/biz"
	"gitlab.calendaria.team/services/tenants/internal/conf"
	"gitlab.calendaria.team/services/tenants/internal/data"
	"gitlab.calendaria.team/services/tenants/internal/server"
	"gitlab.calendaria.team/services/tenants/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	config, err := data.NewConfig(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	jwtProcessor, err := data.NewJwtProcessor(config)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	tenantsRepo := data.NewTenantsRepo(dataData)
	tenantsUsecase, err := biz.NewTenantsUsecase(logger, config, jwtProcessor, tenantsRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dialer, err := data.NewDialer(config, jwtProcessor)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	membersRepo := data.NewMembersRepo(dataData)
	membersUsecase, err := biz.NewMembersUsecase(logger, jwtProcessor, dialer, tenantsRepo, membersRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	tenantsService := service.NewTenantsService(tenantsUsecase, membersUsecase)
	membersService := service.NewMembersService(membersUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, logger, jwtProcessor, tenantsService, membersService)
	httpServer := server.NewHTTPServer(bootstrap, logger, jwtProcessor, tenantsService, membersService)
	app := newApp(logger, config, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
