// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package tenants_v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

// Set the error code separately for an enumeration.
func IsInternal(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INTERNAL.String() && e.Code == 500
}

// Set the error code separately for an enumeration.
func ErrorInternal(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_INTERNAL.String(), fmt.Sprintf(format, args...))
}

func IsGrpcConnection(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_GRPC_CONNECTION.String() && e.Code == 500
}

func ErrorGrpcConnection(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_GRPC_CONNECTION.String(), fmt.Sprintf(format, args...))
}

func IsServiceFailed(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_SERVICE_FAILED.String() && e.Code == 500
}

func ErrorServiceFailed(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_SERVICE_FAILED.String(), fmt.Sprintf(format, args...))
}

func IsDatabaseQuery(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_DATABASE_QUERY.String() && e.Code == 500
}

func ErrorDatabaseQuery(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_DATABASE_QUERY.String(), fmt.Sprintf(format, args...))
}

func IsUnauthorized(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNAUTHORIZED.String() && e.Code == 401
}

func ErrorUnauthorized(format string, args ...interface{}) *errors.Error {
	return errors.New(401, ErrorReason_UNAUTHORIZED.String(), fmt.Sprintf(format, args...))
}

func IsNotFound(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_NOT_FOUND.String() && e.Code == 404
}

func ErrorNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}

func IsForbidden(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_FORBIDDEN.String() && e.Code == 403
}

func ErrorForbidden(format string, args ...interface{}) *errors.Error {
	return errors.New(403, ErrorReason_FORBIDDEN.String(), fmt.Sprintf(format, args...))
}

func IsInvalidRequest(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_INVALID_REQUEST.String() && e.Code == 400
}

func ErrorInvalidRequest(format string, args ...interface{}) *errors.Error {
	return errors.New(400, ErrorReason_INVALID_REQUEST.String(), fmt.Sprintf(format, args...))
}

func IsResourceAlreadyExists(err error) bool {
	if err == nil {
		return false
	}
	e := errors.FromError(err)
	return e.Reason == ErrorReason_RESOURCE_ALREADY_EXISTS.String() && e.Code == 409
}

func ErrorResourceAlreadyExists(format string, args ...interface{}) *errors.Error {
	return errors.New(409, ErrorReason_RESOURCE_ALREADY_EXISTS.String(), fmt.Sprintf(format, args...))
}
