// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v4.25.0
// source: api/tenants/v1/invites.proto

package tenants_v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationInvitesCreateInvites = "/tenants.v1.Invites/CreateInvites"
const OperationInvitesDeleteInvite = "/tenants.v1.Invites/DeleteInvite"
const OperationInvitesListInvites = "/tenants.v1.Invites/ListInvites"
const OperationInvitesUpdateInvite = "/tenants.v1.Invites/UpdateInvite"

type InvitesHTTPServer interface {
	CreateInvites(context.Context, *CreateInvitesRequest) (*ListInvitesReply, error)
	DeleteInvite(context.Context, *DeleteInviteRequest) (*v1.EmptyReply, error)
	ListInvites(context.Context, *ListInvitesRequest) (*ListInvitesReply, error)
	UpdateInvite(context.Context, *UpdateInviteRequest) (*v1.EmptyReply, error)
}

func RegisterInvitesHTTPServer(s *http.Server, srv InvitesHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/tenants/invites", _Invites_CreateInvites0_HTTP_Handler(srv))
	r.PUT("/v1/tenants/invites/{inviteId}", _Invites_UpdateInvite0_HTTP_Handler(srv))
	r.DELETE("/v1/tenants/invites/{inviteId}", _Invites_DeleteInvite0_HTTP_Handler(srv))
	r.POST("/v1/tenants/invites/list", _Invites_ListInvites0_HTTP_Handler(srv))
}

func _Invites_CreateInvites0_HTTP_Handler(srv InvitesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateInvitesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInvitesCreateInvites)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateInvites(ctx, req.(*CreateInvitesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListInvitesReply)
		return ctx.Result(200, reply)
	}
}

func _Invites_UpdateInvite0_HTTP_Handler(srv InvitesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateInviteRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInvitesUpdateInvite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateInvite(ctx, req.(*UpdateInviteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Invites_DeleteInvite0_HTTP_Handler(srv InvitesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteInviteRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInvitesDeleteInvite)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteInvite(ctx, req.(*DeleteInviteRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Invites_ListInvites0_HTTP_Handler(srv InvitesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListInvitesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationInvitesListInvites)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListInvites(ctx, req.(*ListInvitesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListInvitesReply)
		return ctx.Result(200, reply)
	}
}

type InvitesHTTPClient interface {
	CreateInvites(ctx context.Context, req *CreateInvitesRequest, opts ...http.CallOption) (rsp *ListInvitesReply, err error)
	DeleteInvite(ctx context.Context, req *DeleteInviteRequest, opts ...http.CallOption) (rsp *v1.EmptyReply, err error)
	ListInvites(ctx context.Context, req *ListInvitesRequest, opts ...http.CallOption) (rsp *ListInvitesReply, err error)
	UpdateInvite(ctx context.Context, req *UpdateInviteRequest, opts ...http.CallOption) (rsp *v1.EmptyReply, err error)
}

type InvitesHTTPClientImpl struct {
	cc *http.Client
}

func NewInvitesHTTPClient(client *http.Client) InvitesHTTPClient {
	return &InvitesHTTPClientImpl{client}
}

func (c *InvitesHTTPClientImpl) CreateInvites(ctx context.Context, in *CreateInvitesRequest, opts ...http.CallOption) (*ListInvitesReply, error) {
	var out ListInvitesReply
	pattern := "/v1/tenants/invites"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInvitesCreateInvites))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InvitesHTTPClientImpl) DeleteInvite(ctx context.Context, in *DeleteInviteRequest, opts ...http.CallOption) (*v1.EmptyReply, error) {
	var out v1.EmptyReply
	pattern := "/v1/tenants/invites/{inviteId}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationInvitesDeleteInvite))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InvitesHTTPClientImpl) ListInvites(ctx context.Context, in *ListInvitesRequest, opts ...http.CallOption) (*ListInvitesReply, error) {
	var out ListInvitesReply
	pattern := "/v1/tenants/invites/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInvitesListInvites))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InvitesHTTPClientImpl) UpdateInvite(ctx context.Context, in *UpdateInviteRequest, opts ...http.CallOption) (*v1.EmptyReply, error) {
	var out v1.EmptyReply
	pattern := "/v1/tenants/invites/{inviteId}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationInvitesUpdateInvite))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
