// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/tenants/v1/invites.proto

package tenants_v1

import (
	v11 "gitlab.calendaria.team/services/iam/api/iam/v1"
	v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_UNSPECIFIED Status = 0
	Status_NEW         Status = 1
	Status_SENT        Status = 2
	Status_SHOWN       Status = 3
	Status_ACCEPTED    Status = 4
	Status_DECLINED    Status = 5
	Status_CANCELED    Status = 6
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "NEW",
		2: "SENT",
		3: "SHOWN",
		4: "ACCEPTED",
		5: "DECLINED",
		6: "CANCELED",
	}
	Status_value = map[string]int32{
		"UNSPECIFIED": 0,
		"NEW":         1,
		"SENT":        2,
		"SHOWN":       3,
		"ACCEPTED":    4,
		"DECLINED":    5,
		"CANCELED":    6,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_tenants_v1_invites_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_tenants_v1_invites_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_tenants_v1_invites_proto_rawDescGZIP(), []int{0}
}

type CreateInvitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emails        []string               `protobuf:"bytes,1,rep,name=emails,proto3" json:"emails,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	RoleId        int64                  `protobuf:"varint,4,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Resource      string                 `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	ResourceId    int64                  `protobuf:"varint,6,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvitesRequest) Reset() {
	*x = CreateInvitesRequest{}
	mi := &file_api_tenants_v1_invites_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvitesRequest) ProtoMessage() {}

func (x *CreateInvitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_invites_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvitesRequest.ProtoReflect.Descriptor instead.
func (*CreateInvitesRequest) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_invites_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInvitesRequest) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *CreateInvitesRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateInvitesRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateInvitesRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *CreateInvitesRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CreateInvitesRequest) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

type InviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteId      int64                  `protobuf:"varint,1,opt,name=inviteId,proto3" json:"inviteId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteRequest) Reset() {
	*x = InviteRequest{}
	mi := &file_api_tenants_v1_invites_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteRequest) ProtoMessage() {}

func (x *InviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_invites_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteRequest.ProtoReflect.Descriptor instead.
func (*InviteRequest) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_invites_proto_rawDescGZIP(), []int{1}
}

func (x *InviteRequest) GetInviteId() int64 {
	if x != nil {
		return x.InviteId
	}
	return 0
}

type ListInvitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=tenants.v1.Status" json:"status,omitempty"`
	Sort          *v1.SortRequest        `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Paginate      *v1.PaginateRequest    `protobuf:"bytes,4,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitesRequest) Reset() {
	*x = ListInvitesRequest{}
	mi := &file_api_tenants_v1_invites_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitesRequest) ProtoMessage() {}

func (x *ListInvitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_invites_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitesRequest.ProtoReflect.Descriptor instead.
func (*ListInvitesRequest) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_invites_proto_rawDescGZIP(), []int{2}
}

func (x *ListInvitesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListInvitesRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNSPECIFIED
}

func (x *ListInvitesRequest) GetSort() *v1.SortRequest {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ListInvitesRequest) GetPaginate() *v1.PaginateRequest {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type ListInvitesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invites       []*Invite              `protobuf:"bytes,1,rep,name=invites,proto3" json:"invites,omitempty"`
	Paginate      *v1.PaginateReply      `protobuf:"bytes,2,opt,name=paginate,proto3,oneof" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitesReply) Reset() {
	*x = ListInvitesReply{}
	mi := &file_api_tenants_v1_invites_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitesReply) ProtoMessage() {}

func (x *ListInvitesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_invites_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitesReply.ProtoReflect.Descriptor instead.
func (*ListInvitesReply) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_invites_proto_rawDescGZIP(), []int{3}
}

func (x *ListInvitesReply) GetInvites() []*Invite {
	if x != nil {
		return x.Invites
	}
	return nil
}

func (x *ListInvitesReply) GetPaginate() *v1.PaginateReply {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type InviteCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteId      int64                  `protobuf:"varint,1,opt,name=inviteId,proto3" json:"inviteId,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteCodeRequest) Reset() {
	*x = InviteCodeRequest{}
	mi := &file_api_tenants_v1_invites_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteCodeRequest) ProtoMessage() {}

func (x *InviteCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_invites_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteCodeRequest.ProtoReflect.Descriptor instead.
func (*InviteCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_invites_proto_rawDescGZIP(), []int{4}
}

func (x *InviteCodeRequest) GetInviteId() int64 {
	if x != nil {
		return x.InviteId
	}
	return 0
}

func (x *InviteCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type InviteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invite        *Invite                `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite,omitempty"`
	Tenant        *Tenant                `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteReply) Reset() {
	*x = InviteReply{}
	mi := &file_api_tenants_v1_invites_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteReply) ProtoMessage() {}

func (x *InviteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_invites_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteReply.ProtoReflect.Descriptor instead.
func (*InviteReply) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_invites_proto_rawDescGZIP(), []int{5}
}

func (x *InviteReply) GetInvite() *Invite {
	if x != nil {
		return x.Invite
	}
	return nil
}

func (x *InviteReply) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type Invite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Status        Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=tenants.v1.Status" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	User          *v11.UserShort         `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invite) Reset() {
	*x = Invite{}
	mi := &file_api_tenants_v1_invites_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invite) ProtoMessage() {}

func (x *Invite) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_invites_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invite.ProtoReflect.Descriptor instead.
func (*Invite) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_invites_proto_rawDescGZIP(), []int{6}
}

func (x *Invite) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Invite) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Invite) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNSPECIFIED
}

func (x *Invite) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Invite) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Invite) GetUser() *v11.UserShort {
	if x != nil {
		return x.User
	}
	return nil
}

var File_api_tenants_v1_invites_proto protoreflect.FileDescriptor

const file_api_tenants_v1_invites_proto_rawDesc = "" +
	"\n" +
	"\x1capi/tenants/v1/invites.proto\x12\n" +
	"tenants.v1\x1a\x19api/utils/v1/models.proto\x1a\x17api/iam/v1/models.proto\x1a\x1bapi/tenants/v1/models.proto\"\xb4\x01\n" +
	"\x14CreateInvitesRequest\x12\x16\n" +
	"\x06emails\x18\x01 \x03(\tR\x06emails\x12\x14\n" +
	"\x05appId\x18\x02 \x01(\tR\x05appId\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x16\n" +
	"\x06roleId\x18\x04 \x01(\x03R\x06roleId\x12\x1a\n" +
	"\bresource\x18\x05 \x01(\tR\bresource\x12\x1e\n" +
	"\n" +
	"resourceId\x18\x06 \x01(\x03R\n" +
	"resourceId\"+\n" +
	"\rInviteRequest\x12\x1a\n" +
	"\binviteId\x18\x01 \x01(\x03R\binviteId\"\xba\x01\n" +
	"\x12ListInvitesRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.tenants.v1.StatusR\x06status\x12)\n" +
	"\x04sort\x18\x03 \x01(\v2\x15.utils.v1.SortRequestR\x04sort\x125\n" +
	"\bpaginate\x18\x04 \x01(\v2\x19.utils.v1.PaginateRequestR\bpaginate\"\x87\x01\n" +
	"\x10ListInvitesReply\x12,\n" +
	"\ainvites\x18\x01 \x03(\v2\x12.tenants.v1.InviteR\ainvites\x128\n" +
	"\bpaginate\x18\x02 \x01(\v2\x17.utils.v1.PaginateReplyH\x00R\bpaginate\x88\x01\x01B\v\n" +
	"\t_paginate\"C\n" +
	"\x11InviteCodeRequest\x12\x1a\n" +
	"\binviteId\x18\x01 \x01(\x03R\binviteId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"e\n" +
	"\vInviteReply\x12*\n" +
	"\x06invite\x18\x01 \x01(\v2\x12.tenants.v1.InviteR\x06invite\x12*\n" +
	"\x06tenant\x18\x02 \x01(\v2\x12.tenants.v1.TenantR\x06tenant\"\xbd\x01\n" +
	"\x06Invite\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12*\n" +
	"\x06status\x18\x03 \x01(\x0e2\x12.tenants.v1.StatusR\x06status\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\tR\tupdatedAt\x12%\n" +
	"\x04user\x18\x06 \x01(\v2\x11.iam.v1.UserShortR\x04user*a\n" +
	"\x06Status\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\a\n" +
	"\x03NEW\x10\x01\x12\b\n" +
	"\x04SENT\x10\x02\x12\t\n" +
	"\x05SHOWN\x10\x03\x12\f\n" +
	"\bACCEPTED\x10\x04\x12\f\n" +
	"\bDECLINED\x10\x05\x12\f\n" +
	"\bCANCELED\x10\x062\xfe\x03\n" +
	"\aInvites\x12O\n" +
	"\rCreateInvites\x12 .tenants.v1.CreateInvitesRequest\x1a\x1c.tenants.v1.ListInvitesReply\x12?\n" +
	"\fCancelInvite\x12\x19.tenants.v1.InviteRequest\x1a\x14.utils.v1.EmptyReply\x12?\n" +
	"\fDeleteInvite\x12\x19.tenants.v1.InviteRequest\x1a\x14.utils.v1.EmptyReply\x12K\n" +
	"\vListInvites\x12\x1e.tenants.v1.ListInvitesRequest\x1a\x1c.tenants.v1.ListInvitesReply\x12F\n" +
	"\fAcceptInvite\x12\x1d.tenants.v1.InviteCodeRequest\x1a\x17.tenants.v1.TenantReply\x12E\n" +
	"\vShownInvite\x12\x1d.tenants.v1.InviteCodeRequest\x1a\x17.tenants.v1.InviteReply\x12D\n" +
	"\rDeclineInvite\x12\x1d.tenants.v1.InviteCodeRequest\x1a\x14.utils.v1.EmptyReplyBQ\n" +
	"\n" +
	"tenants.v1P\x01ZAgitlab.calendaria.team/services/tenants/api/tenants/v1;tenants_v1b\x06proto3"

var (
	file_api_tenants_v1_invites_proto_rawDescOnce sync.Once
	file_api_tenants_v1_invites_proto_rawDescData []byte
)

func file_api_tenants_v1_invites_proto_rawDescGZIP() []byte {
	file_api_tenants_v1_invites_proto_rawDescOnce.Do(func() {
		file_api_tenants_v1_invites_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tenants_v1_invites_proto_rawDesc), len(file_api_tenants_v1_invites_proto_rawDesc)))
	})
	return file_api_tenants_v1_invites_proto_rawDescData
}

var file_api_tenants_v1_invites_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_tenants_v1_invites_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_tenants_v1_invites_proto_goTypes = []any{
	(Status)(0),                  // 0: tenants.v1.Status
	(*CreateInvitesRequest)(nil), // 1: tenants.v1.CreateInvitesRequest
	(*InviteRequest)(nil),        // 2: tenants.v1.InviteRequest
	(*ListInvitesRequest)(nil),   // 3: tenants.v1.ListInvitesRequest
	(*ListInvitesReply)(nil),     // 4: tenants.v1.ListInvitesReply
	(*InviteCodeRequest)(nil),    // 5: tenants.v1.InviteCodeRequest
	(*InviteReply)(nil),          // 6: tenants.v1.InviteReply
	(*Invite)(nil),               // 7: tenants.v1.Invite
	(*v1.SortRequest)(nil),       // 8: utils.v1.SortRequest
	(*v1.PaginateRequest)(nil),   // 9: utils.v1.PaginateRequest
	(*v1.PaginateReply)(nil),     // 10: utils.v1.PaginateReply
	(*Tenant)(nil),               // 11: tenants.v1.Tenant
	(*v11.UserShort)(nil),        // 12: iam.v1.UserShort
	(*v1.EmptyReply)(nil),        // 13: utils.v1.EmptyReply
	(*TenantReply)(nil),          // 14: tenants.v1.TenantReply
}
var file_api_tenants_v1_invites_proto_depIdxs = []int32{
	0,  // 0: tenants.v1.ListInvitesRequest.status:type_name -> tenants.v1.Status
	8,  // 1: tenants.v1.ListInvitesRequest.sort:type_name -> utils.v1.SortRequest
	9,  // 2: tenants.v1.ListInvitesRequest.paginate:type_name -> utils.v1.PaginateRequest
	7,  // 3: tenants.v1.ListInvitesReply.invites:type_name -> tenants.v1.Invite
	10, // 4: tenants.v1.ListInvitesReply.paginate:type_name -> utils.v1.PaginateReply
	7,  // 5: tenants.v1.InviteReply.invite:type_name -> tenants.v1.Invite
	11, // 6: tenants.v1.InviteReply.tenant:type_name -> tenants.v1.Tenant
	0,  // 7: tenants.v1.Invite.status:type_name -> tenants.v1.Status
	12, // 8: tenants.v1.Invite.user:type_name -> iam.v1.UserShort
	1,  // 9: tenants.v1.Invites.CreateInvites:input_type -> tenants.v1.CreateInvitesRequest
	2,  // 10: tenants.v1.Invites.CancelInvite:input_type -> tenants.v1.InviteRequest
	2,  // 11: tenants.v1.Invites.DeleteInvite:input_type -> tenants.v1.InviteRequest
	3,  // 12: tenants.v1.Invites.ListInvites:input_type -> tenants.v1.ListInvitesRequest
	5,  // 13: tenants.v1.Invites.AcceptInvite:input_type -> tenants.v1.InviteCodeRequest
	5,  // 14: tenants.v1.Invites.ShownInvite:input_type -> tenants.v1.InviteCodeRequest
	5,  // 15: tenants.v1.Invites.DeclineInvite:input_type -> tenants.v1.InviteCodeRequest
	4,  // 16: tenants.v1.Invites.CreateInvites:output_type -> tenants.v1.ListInvitesReply
	13, // 17: tenants.v1.Invites.CancelInvite:output_type -> utils.v1.EmptyReply
	13, // 18: tenants.v1.Invites.DeleteInvite:output_type -> utils.v1.EmptyReply
	4,  // 19: tenants.v1.Invites.ListInvites:output_type -> tenants.v1.ListInvitesReply
	14, // 20: tenants.v1.Invites.AcceptInvite:output_type -> tenants.v1.TenantReply
	6,  // 21: tenants.v1.Invites.ShownInvite:output_type -> tenants.v1.InviteReply
	13, // 22: tenants.v1.Invites.DeclineInvite:output_type -> utils.v1.EmptyReply
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_tenants_v1_invites_proto_init() }
func file_api_tenants_v1_invites_proto_init() {
	if File_api_tenants_v1_invites_proto != nil {
		return
	}
	file_api_tenants_v1_models_proto_init()
	file_api_tenants_v1_invites_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tenants_v1_invites_proto_rawDesc), len(file_api_tenants_v1_invites_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tenants_v1_invites_proto_goTypes,
		DependencyIndexes: file_api_tenants_v1_invites_proto_depIdxs,
		EnumInfos:         file_api_tenants_v1_invites_proto_enumTypes,
		MessageInfos:      file_api_tenants_v1_invites_proto_msgTypes,
	}.Build()
	File_api_tenants_v1_invites_proto = out.File
	file_api_tenants_v1_invites_proto_goTypes = nil
	file_api_tenants_v1_invites_proto_depIdxs = nil
}
