// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: api/tenants/v1/members.proto

package tenants_v1

import (
	context "context"
	v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Members_CreateMembers_FullMethodName       = "/tenants.v1.Members/CreateMembers"
	Members_DeleteMember_FullMethodName        = "/tenants.v1.Members/DeleteMember"
	Members_GetMember_FullMethodName           = "/tenants.v1.Members/GetMember"
	Members_GetShortMembers_FullMethodName     = "/tenants.v1.Members/GetShortMembers"
	Members_GetMemberIdentities_FullMethodName = "/tenants.v1.Members/GetMemberIdentities"
	Members_ListMembers_FullMethodName         = "/tenants.v1.Members/ListMembers"
	Members_CountMembers_FullMethodName        = "/tenants.v1.Members/CountMembers"
)

// MembersClient is the client API for Members service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MembersClient interface {
	CreateMembers(ctx context.Context, in *CreateMembersRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error)
	DeleteMember(ctx context.Context, in *MemberRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error)
	GetMember(ctx context.Context, in *MemberRequest, opts ...grpc.CallOption) (*MemberReply, error)
	GetShortMembers(ctx context.Context, in *IdentitiesRequest, opts ...grpc.CallOption) (*MembersReply, error)
	GetMemberIdentities(ctx context.Context, in *GetMemberIdentitiesRequest, opts ...grpc.CallOption) (*GetMemberIdentitiesReply, error)
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersReply, error)
	CountMembers(ctx context.Context, in *v1.EmptyRequest, opts ...grpc.CallOption) (*CountMembersReply, error)
}

type membersClient struct {
	cc grpc.ClientConnInterface
}

func NewMembersClient(cc grpc.ClientConnInterface) MembersClient {
	return &membersClient{cc}
}

func (c *membersClient) CreateMembers(ctx context.Context, in *CreateMembersRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.EmptyReply)
	err := c.cc.Invoke(ctx, Members_CreateMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membersClient) DeleteMember(ctx context.Context, in *MemberRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.EmptyReply)
	err := c.cc.Invoke(ctx, Members_DeleteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membersClient) GetMember(ctx context.Context, in *MemberRequest, opts ...grpc.CallOption) (*MemberReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemberReply)
	err := c.cc.Invoke(ctx, Members_GetMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membersClient) GetShortMembers(ctx context.Context, in *IdentitiesRequest, opts ...grpc.CallOption) (*MembersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembersReply)
	err := c.cc.Invoke(ctx, Members_GetShortMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membersClient) GetMemberIdentities(ctx context.Context, in *GetMemberIdentitiesRequest, opts ...grpc.CallOption) (*GetMemberIdentitiesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemberIdentitiesReply)
	err := c.cc.Invoke(ctx, Members_GetMemberIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membersClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersReply)
	err := c.cc.Invoke(ctx, Members_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *membersClient) CountMembers(ctx context.Context, in *v1.EmptyRequest, opts ...grpc.CallOption) (*CountMembersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountMembersReply)
	err := c.cc.Invoke(ctx, Members_CountMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MembersServer is the server API for Members service.
// All implementations must embed UnimplementedMembersServer
// for forward compatibility.
type MembersServer interface {
	CreateMembers(context.Context, *CreateMembersRequest) (*v1.EmptyReply, error)
	DeleteMember(context.Context, *MemberRequest) (*v1.EmptyReply, error)
	GetMember(context.Context, *MemberRequest) (*MemberReply, error)
	GetShortMembers(context.Context, *IdentitiesRequest) (*MembersReply, error)
	GetMemberIdentities(context.Context, *GetMemberIdentitiesRequest) (*GetMemberIdentitiesReply, error)
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersReply, error)
	CountMembers(context.Context, *v1.EmptyRequest) (*CountMembersReply, error)
	mustEmbedUnimplementedMembersServer()
}

// UnimplementedMembersServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMembersServer struct{}

func (UnimplementedMembersServer) CreateMembers(context.Context, *CreateMembersRequest) (*v1.EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMembers not implemented")
}
func (UnimplementedMembersServer) DeleteMember(context.Context, *MemberRequest) (*v1.EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMember not implemented")
}
func (UnimplementedMembersServer) GetMember(context.Context, *MemberRequest) (*MemberReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMember not implemented")
}
func (UnimplementedMembersServer) GetShortMembers(context.Context, *IdentitiesRequest) (*MembersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShortMembers not implemented")
}
func (UnimplementedMembersServer) GetMemberIdentities(context.Context, *GetMemberIdentitiesRequest) (*GetMemberIdentitiesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemberIdentities not implemented")
}
func (UnimplementedMembersServer) ListMembers(context.Context, *ListMembersRequest) (*ListMembersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedMembersServer) CountMembers(context.Context, *v1.EmptyRequest) (*CountMembersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountMembers not implemented")
}
func (UnimplementedMembersServer) mustEmbedUnimplementedMembersServer() {}
func (UnimplementedMembersServer) testEmbeddedByValue()                 {}

// UnsafeMembersServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MembersServer will
// result in compilation errors.
type UnsafeMembersServer interface {
	mustEmbedUnimplementedMembersServer()
}

func RegisterMembersServer(s grpc.ServiceRegistrar, srv MembersServer) {
	// If the following call pancis, it indicates UnimplementedMembersServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Members_ServiceDesc, srv)
}

func _Members_CreateMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembersServer).CreateMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Members_CreateMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembersServer).CreateMembers(ctx, req.(*CreateMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Members_DeleteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembersServer).DeleteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Members_DeleteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembersServer).DeleteMember(ctx, req.(*MemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Members_GetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembersServer).GetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Members_GetMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembersServer).GetMember(ctx, req.(*MemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Members_GetShortMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembersServer).GetShortMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Members_GetShortMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembersServer).GetShortMembers(ctx, req.(*IdentitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Members_GetMemberIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberIdentitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembersServer).GetMemberIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Members_GetMemberIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembersServer).GetMemberIdentities(ctx, req.(*GetMemberIdentitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Members_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembersServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Members_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembersServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Members_CountMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MembersServer).CountMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Members_CountMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MembersServer).CountMembers(ctx, req.(*v1.EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Members_ServiceDesc is the grpc.ServiceDesc for Members service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Members_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tenants.v1.Members",
	HandlerType: (*MembersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMembers",
			Handler:    _Members_CreateMembers_Handler,
		},
		{
			MethodName: "DeleteMember",
			Handler:    _Members_DeleteMember_Handler,
		},
		{
			MethodName: "GetMember",
			Handler:    _Members_GetMember_Handler,
		},
		{
			MethodName: "GetShortMembers",
			Handler:    _Members_GetShortMembers_Handler,
		},
		{
			MethodName: "GetMemberIdentities",
			Handler:    _Members_GetMemberIdentities_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _Members_ListMembers_Handler,
		},
		{
			MethodName: "CountMembers",
			Handler:    _Members_CountMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tenants/v1/members.proto",
}
