// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/tenants/v1/models.proto

package tenants_v1

import (
	v1 "gitlab.calendaria.team/services/iam/api/iam/v1"
	v11 "gitlab.calendaria.team/services/utils/api/utils/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberShort) Reset() {
	*x = MemberShort{}
	mi := &file_api_tenants_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberShort) ProtoMessage() {}

func (x *MemberShort) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberShort.ProtoReflect.Descriptor instead.
func (*MemberShort) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *MemberShort) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberShort) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	ReferredBy    *int64                 `protobuf:"varint,6,opt,name=referredBy,proto3,oneof" json:"referredBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_api_tenants_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *Tenant) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tenant) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Tenant) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Tenant) GetReferredBy() int64 {
	if x != nil && x.ReferredBy != nil {
		return *x.ReferredBy
	}
	return 0
}

type Store struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Lat           *float64               `protobuf:"fixed64,5,opt,name=lat,proto3,oneof" json:"lat,omitempty"`
	Lon           *float64               `protobuf:"fixed64,6,opt,name=lon,proto3,oneof" json:"lon,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	WorkHours     string                 `protobuf:"bytes,8,opt,name=workHours,proto3" json:"workHours,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=isActive,proto3" json:"isActive,omitempty"`
	ResponsibleId *int64                 `protobuf:"varint,10,opt,name=responsibleId,proto3,oneof" json:"responsibleId,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_api_tenants_v1_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_models_proto_rawDescGZIP(), []int{2}
}

func (x *Store) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Store) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Store) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Store) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Store) GetLat() float64 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *Store) GetLon() float64 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

func (x *Store) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Store) GetWorkHours() string {
	if x != nil {
		return x.WorkHours
	}
	return ""
}

func (x *Store) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Store) GetResponsibleId() int64 {
	if x != nil && x.ResponsibleId != nil {
		return *x.ResponsibleId
	}
	return 0
}

func (x *Store) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Store) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TenantReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantReply) Reset() {
	*x = TenantReply{}
	mi := &file_api_tenants_v1_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantReply) ProtoMessage() {}

func (x *TenantReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantReply.ProtoReflect.Descriptor instead.
func (*TenantReply) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_models_proto_rawDescGZIP(), []int{3}
}

func (x *TenantReply) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdentityId    string                 `protobuf:"bytes,2,opt,name=identityId,proto3" json:"identityId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_api_tenants_v1_models_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_models_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_models_proto_rawDescGZIP(), []int{4}
}

func (x *Group) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Group) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Group) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Group) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TenantMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,2,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	IdentityId    *string                `protobuf:"bytes,3,opt,name=identityId,proto3,oneof" json:"identityId,omitempty"`
	User          *v1.UserShort          `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Groups        []int64                `protobuf:"varint,5,rep,packed,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantMember) Reset() {
	*x = TenantMember{}
	mi := &file_api_tenants_v1_models_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantMember) ProtoMessage() {}

func (x *TenantMember) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_models_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantMember.ProtoReflect.Descriptor instead.
func (*TenantMember) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_models_proto_rawDescGZIP(), []int{5}
}

func (x *TenantMember) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TenantMember) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TenantMember) GetIdentityId() string {
	if x != nil && x.IdentityId != nil {
		return *x.IdentityId
	}
	return ""
}

func (x *TenantMember) GetUser() *v1.UserShort {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *TenantMember) GetGroups() []int64 {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ListMembersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*TenantMember        `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Groups        []*Group               `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
	Paginate      *v11.PaginateReply     `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersReply) Reset() {
	*x = ListMembersReply{}
	mi := &file_api_tenants_v1_models_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersReply) ProtoMessage() {}

func (x *ListMembersReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_models_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersReply.ProtoReflect.Descriptor instead.
func (*ListMembersReply) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_models_proto_rawDescGZIP(), []int{6}
}

func (x *ListMembersReply) GetMembers() []*TenantMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *ListMembersReply) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ListMembersReply) GetPaginate() *v11.PaginateReply {
	if x != nil {
		return x.Paginate
	}
	return nil
}

var File_api_tenants_v1_models_proto protoreflect.FileDescriptor

const file_api_tenants_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/tenants/v1/models.proto\x12\n" +
	"tenants.v1\x1a\x19api/utils/v1/models.proto\x1a\x17api/iam/v1/models.proto\"5\n" +
	"\vMemberShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\"\xac\x01\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aownerId\x18\x02 \x01(\x03R\aownerId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12#\n" +
	"\n" +
	"referredBy\x18\x06 \x01(\x03H\x00R\n" +
	"referredBy\x88\x01\x01B\r\n" +
	"\v_referredBy\"\xe8\x02\n" +
	"\x05Store\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\btenantId\x18\x02 \x01(\x03R\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x15\n" +
	"\x03lat\x18\x05 \x01(\x01H\x00R\x03lat\x88\x01\x01\x12\x15\n" +
	"\x03lon\x18\x06 \x01(\x01H\x01R\x03lon\x88\x01\x01\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x1c\n" +
	"\tworkHours\x18\b \x01(\tR\tworkHours\x12\x1a\n" +
	"\bisActive\x18\t \x01(\bR\bisActive\x12)\n" +
	"\rresponsibleId\x18\n" +
	" \x01(\x03H\x02R\rresponsibleId\x88\x01\x01\x12\x1c\n" +
	"\tcreatedAt\x18\v \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\f \x01(\tR\tupdatedAtB\x06\n" +
	"\x04_latB\x06\n" +
	"\x04_lonB\x10\n" +
	"\x0e_responsibleId\"9\n" +
	"\vTenantReply\x12*\n" +
	"\x06tenant\x18\x01 \x01(\v2\x12.tenants.v1.TenantR\x06tenant\"\xa9\x01\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1e\n" +
	"\n" +
	"identityId\x18\x02 \x01(\tR\n" +
	"identityId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\tcreatedAt\x18\x05 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x06 \x01(\tR\tupdatedAt\"\xaf\x01\n" +
	"\fTenantMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tcreatedAt\x18\x02 \x01(\tR\tcreatedAt\x12#\n" +
	"\n" +
	"identityId\x18\x03 \x01(\tH\x00R\n" +
	"identityId\x88\x01\x01\x12%\n" +
	"\x04user\x18\x04 \x01(\v2\x11.iam.v1.UserShortR\x04user\x12\x16\n" +
	"\x06groups\x18\x05 \x03(\x03R\x06groupsB\r\n" +
	"\v_identityId\"\xa6\x01\n" +
	"\x10ListMembersReply\x122\n" +
	"\amembers\x18\x01 \x03(\v2\x18.tenants.v1.TenantMemberR\amembers\x12)\n" +
	"\x06groups\x18\x03 \x03(\v2\x11.tenants.v1.GroupR\x06groups\x123\n" +
	"\bpaginate\x18\x02 \x01(\v2\x17.utils.v1.PaginateReplyR\bpaginateBQ\n" +
	"\n" +
	"tenants.v1P\x01ZAgitlab.calendaria.team/services/tenants/api/tenants/v1;tenants_v1b\x06proto3"

var (
	file_api_tenants_v1_models_proto_rawDescOnce sync.Once
	file_api_tenants_v1_models_proto_rawDescData []byte
)

func file_api_tenants_v1_models_proto_rawDescGZIP() []byte {
	file_api_tenants_v1_models_proto_rawDescOnce.Do(func() {
		file_api_tenants_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tenants_v1_models_proto_rawDesc), len(file_api_tenants_v1_models_proto_rawDesc)))
	})
	return file_api_tenants_v1_models_proto_rawDescData
}

var file_api_tenants_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_tenants_v1_models_proto_goTypes = []any{
	(*MemberShort)(nil),       // 0: tenants.v1.MemberShort
	(*Tenant)(nil),            // 1: tenants.v1.Tenant
	(*Store)(nil),             // 2: tenants.v1.Store
	(*TenantReply)(nil),       // 3: tenants.v1.TenantReply
	(*Group)(nil),             // 4: tenants.v1.Group
	(*TenantMember)(nil),      // 5: tenants.v1.TenantMember
	(*ListMembersReply)(nil),  // 6: tenants.v1.ListMembersReply
	(*v1.UserShort)(nil),      // 7: iam.v1.UserShort
	(*v11.PaginateReply)(nil), // 8: utils.v1.PaginateReply
}
var file_api_tenants_v1_models_proto_depIdxs = []int32{
	1, // 0: tenants.v1.TenantReply.tenant:type_name -> tenants.v1.Tenant
	7, // 1: tenants.v1.TenantMember.user:type_name -> iam.v1.UserShort
	5, // 2: tenants.v1.ListMembersReply.members:type_name -> tenants.v1.TenantMember
	4, // 3: tenants.v1.ListMembersReply.groups:type_name -> tenants.v1.Group
	8, // 4: tenants.v1.ListMembersReply.paginate:type_name -> utils.v1.PaginateReply
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_tenants_v1_models_proto_init() }
func file_api_tenants_v1_models_proto_init() {
	if File_api_tenants_v1_models_proto != nil {
		return
	}
	file_api_tenants_v1_models_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_tenants_v1_models_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_tenants_v1_models_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tenants_v1_models_proto_rawDesc), len(file_api_tenants_v1_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_tenants_v1_models_proto_goTypes,
		DependencyIndexes: file_api_tenants_v1_models_proto_depIdxs,
		MessageInfos:      file_api_tenants_v1_models_proto_msgTypes,
	}.Build()
	File_api_tenants_v1_models_proto = out.File
	file_api_tenants_v1_models_proto_goTypes = nil
	file_api_tenants_v1_models_proto_depIdxs = nil
}
