// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: api/tenants/v1/stores.proto

package tenants_v1

import (
	context "context"
	v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Stores_CreateStore_FullMethodName         = "/tenants.v1.Stores/CreateStore"
	Stores_UpdateStore_FullMethodName         = "/tenants.v1.Stores/UpdateStore"
	Stores_DeleteStore_FullMethodName         = "/tenants.v1.Stores/DeleteStore"
	Stores_GetStore_FullMethodName            = "/tenants.v1.Stores/GetStore"
	Stores_ListStores_FullMethodName          = "/tenants.v1.Stores/ListStores"
	Stores_SetStoreResponsible_FullMethodName = "/tenants.v1.Stores/SetStoreResponsible"
)

// StoresClient is the client API for Stores service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoresClient interface {
	CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*StoreReply, error)
	UpdateStore(ctx context.Context, in *UpdateStoreRequest, opts ...grpc.CallOption) (*StoreReply, error)
	DeleteStore(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error)
	GetStore(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreReply, error)
	ListStores(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresReply, error)
	SetStoreResponsible(ctx context.Context, in *SetStoreResponsibleRequest, opts ...grpc.CallOption) (*StoreReply, error)
}

type storesClient struct {
	cc grpc.ClientConnInterface
}

func NewStoresClient(cc grpc.ClientConnInterface) StoresClient {
	return &storesClient{cc}
}

func (c *storesClient) CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*StoreReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreReply)
	err := c.cc.Invoke(ctx, Stores_CreateStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesClient) UpdateStore(ctx context.Context, in *UpdateStoreRequest, opts ...grpc.CallOption) (*StoreReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreReply)
	err := c.cc.Invoke(ctx, Stores_UpdateStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesClient) DeleteStore(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.EmptyReply)
	err := c.cc.Invoke(ctx, Stores_DeleteStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesClient) GetStore(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreReply)
	err := c.cc.Invoke(ctx, Stores_GetStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesClient) ListStores(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStoresReply)
	err := c.cc.Invoke(ctx, Stores_ListStores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storesClient) SetStoreResponsible(ctx context.Context, in *SetStoreResponsibleRequest, opts ...grpc.CallOption) (*StoreReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreReply)
	err := c.cc.Invoke(ctx, Stores_SetStoreResponsible_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoresServer is the server API for Stores service.
// All implementations must embed UnimplementedStoresServer
// for forward compatibility.
type StoresServer interface {
	CreateStore(context.Context, *CreateStoreRequest) (*StoreReply, error)
	UpdateStore(context.Context, *UpdateStoreRequest) (*StoreReply, error)
	DeleteStore(context.Context, *StoreRequest) (*v1.EmptyReply, error)
	GetStore(context.Context, *StoreRequest) (*StoreReply, error)
	ListStores(context.Context, *ListStoresRequest) (*ListStoresReply, error)
	SetStoreResponsible(context.Context, *SetStoreResponsibleRequest) (*StoreReply, error)
	mustEmbedUnimplementedStoresServer()
}

// UnimplementedStoresServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoresServer struct{}

func (UnimplementedStoresServer) CreateStore(context.Context, *CreateStoreRequest) (*StoreReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateStore not implemented")
}
func (UnimplementedStoresServer) UpdateStore(context.Context, *UpdateStoreRequest) (*StoreReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStore not implemented")
}
func (UnimplementedStoresServer) DeleteStore(context.Context, *StoreRequest) (*v1.EmptyReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStore not implemented")
}
func (UnimplementedStoresServer) GetStore(context.Context, *StoreRequest) (*StoreReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStore not implemented")
}
func (UnimplementedStoresServer) ListStores(context.Context, *ListStoresRequest) (*ListStoresReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStores not implemented")
}
func (UnimplementedStoresServer) SetStoreResponsible(context.Context, *SetStoreResponsibleRequest) (*StoreReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetStoreResponsible not implemented")
}
func (UnimplementedStoresServer) mustEmbedUnimplementedStoresServer() {}
func (UnimplementedStoresServer) testEmbeddedByValue()                {}

// UnsafeStoresServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoresServer will
// result in compilation errors.
type UnsafeStoresServer interface {
	mustEmbedUnimplementedStoresServer()
}

func RegisterStoresServer(s grpc.ServiceRegistrar, srv StoresServer) {
	// If the following call panics, it indicates UnimplementedStoresServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Stores_ServiceDesc, srv)
}

func _Stores_CreateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServer).CreateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stores_CreateStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServer).CreateStore(ctx, req.(*CreateStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stores_UpdateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServer).UpdateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stores_UpdateStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServer).UpdateStore(ctx, req.(*UpdateStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stores_DeleteStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServer).DeleteStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stores_DeleteStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServer).DeleteStore(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stores_GetStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServer).GetStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stores_GetStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServer).GetStore(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stores_ListStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServer).ListStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stores_ListStores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServer).ListStores(ctx, req.(*ListStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stores_SetStoreResponsible_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStoreResponsibleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoresServer).SetStoreResponsible(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stores_SetStoreResponsible_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoresServer).SetStoreResponsible(ctx, req.(*SetStoreResponsibleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Stores_ServiceDesc is the grpc.ServiceDesc for Stores service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stores_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tenants.v1.Stores",
	HandlerType: (*StoresServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateStore",
			Handler:    _Stores_CreateStore_Handler,
		},
		{
			MethodName: "UpdateStore",
			Handler:    _Stores_UpdateStore_Handler,
		},
		{
			MethodName: "DeleteStore",
			Handler:    _Stores_DeleteStore_Handler,
		},
		{
			MethodName: "GetStore",
			Handler:    _Stores_GetStore_Handler,
		},
		{
			MethodName: "ListStores",
			Handler:    _Stores_ListStores_Handler,
		},
		{
			MethodName: "SetStoreResponsible",
			Handler:    _Stores_SetStoreResponsible_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tenants/v1/stores.proto",
}
