// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: tenants/v1/tenants.proto

package tenants_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Tenants_CreateTenant_FullMethodName  = "/api.tenants.v1.tenants/CreateTenant"
	Tenants_UpdateTenant_FullMethodName  = "/api.tenants.v1.tenants/UpdateTenant"
	Tenants_DeleteTenant_FullMethodName  = "/api.tenants.v1.tenants/DeleteTenant"
	Tenants_GetTenant_FullMethodName     = "/api.tenants.v1.tenants/GetTenant"
	Tenants_GetTenantTree_FullMethodName = "/api.tenants.v1.tenants/GetTenantTree"
	Tenants_Listtenants_FullMethodName   = "/api.tenants.v1.tenants/Listtenants"
)

// TenantsClient is the client API for Tenants service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantsClient interface {
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*TenantReply, error)
	UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*TenantReply, error)
	DeleteTenant(ctx context.Context, in *TenantRequest, opts ...grpc.CallOption) (*EmptyReply, error)
	GetTenant(ctx context.Context, in *TenantRequest, opts ...grpc.CallOption) (*TenantReply, error)
	GetTenantTree(ctx context.Context, in *TenantRequest, opts ...grpc.CallOption) (*TenantReply, error)
	Listtenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsReply, error)
}

type tenantsClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantsClient(cc grpc.ClientConnInterface) TenantsClient {
	return &tenantsClient{cc}
}

func (c *tenantsClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*TenantReply, error) {
	out := new(TenantReply)
	err := c.cc.Invoke(ctx, Tenants_CreateTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsClient) UpdateTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*TenantReply, error) {
	out := new(TenantReply)
	err := c.cc.Invoke(ctx, Tenants_UpdateTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsClient) DeleteTenant(ctx context.Context, in *TenantRequest, opts ...grpc.CallOption) (*EmptyReply, error) {
	out := new(EmptyReply)
	err := c.cc.Invoke(ctx, Tenants_DeleteTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsClient) GetTenant(ctx context.Context, in *TenantRequest, opts ...grpc.CallOption) (*TenantReply, error) {
	out := new(TenantReply)
	err := c.cc.Invoke(ctx, Tenants_GetTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsClient) GetTenantTree(ctx context.Context, in *TenantRequest, opts ...grpc.CallOption) (*TenantReply, error) {
	out := new(TenantReply)
	err := c.cc.Invoke(ctx, Tenants_GetTenantTree_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsClient) Listtenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsReply, error) {
	out := new(ListTenantsReply)
	err := c.cc.Invoke(ctx, Tenants_Listtenants_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantsServer is the server API for Tenants service.
// All implementations must embed UnimplementedTenantsServer
// for forward compatibility
type TenantsServer interface {
	CreateTenant(context.Context, *CreateTenantRequest) (*TenantReply, error)
	UpdateTenant(context.Context, *UpdateTenantRequest) (*TenantReply, error)
	DeleteTenant(context.Context, *TenantRequest) (*EmptyReply, error)
	GetTenant(context.Context, *TenantRequest) (*TenantReply, error)
	GetTenantTree(context.Context, *TenantRequest) (*TenantReply, error)
	Listtenants(context.Context, *ListTenantsRequest) (*ListTenantsReply, error)
	mustEmbedUnimplementedTenantsServer()
}

// UnimplementedTenantsServer must be embedded to have forward compatible implementations.
type UnimplementedTenantsServer struct {
}

func (UnimplementedTenantsServer) CreateTenant(context.Context, *CreateTenantRequest) (*TenantReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedTenantsServer) UpdateTenant(context.Context, *UpdateTenantRequest) (*TenantReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTenant not implemented")
}
func (UnimplementedTenantsServer) DeleteTenant(context.Context, *TenantRequest) (*EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTenant not implemented")
}
func (UnimplementedTenantsServer) GetTenant(context.Context, *TenantRequest) (*TenantReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedTenantsServer) GetTenantTree(context.Context, *TenantRequest) (*TenantReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTenantTree not implemented")
}
func (UnimplementedTenantsServer) Listtenants(context.Context, *ListTenantsRequest) (*ListTenantsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Listtenants not implemented")
}
func (UnimplementedTenantsServer) mustEmbedUnimplementedTenantsServer() {}

// UnsafeTenantsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantsServer will
// result in compilation errors.
type UnsafeTenantsServer interface {
	mustEmbedUnimplementedTenantsServer()
}

func RegisterTenantsServer(s grpc.ServiceRegistrar, srv TenantsServer) {
	s.RegisterService(&Tenants_ServiceDesc, srv)
}

func _Tenants_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenants_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenants_UpdateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).UpdateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenants_UpdateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).UpdateTenant(ctx, req.(*UpdateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenants_DeleteTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).DeleteTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenants_DeleteTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).DeleteTenant(ctx, req.(*TenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenants_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenants_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).GetTenant(ctx, req.(*TenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenants_GetTenantTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).GetTenantTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenants_GetTenantTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).GetTenantTree(ctx, req.(*TenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenants_Listtenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).Listtenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenants_Listtenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).Listtenants(ctx, req.(*ListTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tenants_ServiceDesc is the grpc.ServiceDesc for Tenants service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tenants_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.tenants.v1.tenants",
	HandlerType: (*TenantsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTenant",
			Handler:    _Tenants_CreateTenant_Handler,
		},
		{
			MethodName: "UpdateTenant",
			Handler:    _Tenants_UpdateTenant_Handler,
		},
		{
			MethodName: "DeleteTenant",
			Handler:    _Tenants_DeleteTenant_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _Tenants_GetTenant_Handler,
		},
		{
			MethodName: "GetTenantTree",
			Handler:    _Tenants_GetTenantTree_Handler,
		},
		{
			MethodName: "Listtenants",
			Handler:    _Tenants_Listtenants_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tenants/v1/tenants.proto",
}
