// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/tenants/v1/tenants.proto

package tenants_v1

import (
	v1 "github.com/makesalekz/utils/api/utils/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // default = PERSONAL
	ReferredBy    *int64                 `protobuf:"varint,3,opt,name=referred_by,json=referredBy,proto3,oneof" json:"referred_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_tenants_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTenantRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateTenantRequest) GetReferredBy() int64 {
	if x != nil && x.ReferredBy != nil {
		return *x.ReferredBy
	}
	return 0
}

type UpdateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantRequest) Reset() {
	*x = UpdateTenantRequest{}
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantRequest) ProtoMessage() {}

func (x *UpdateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantRequest) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_tenants_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateTenantRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *UpdateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantRequest) Reset() {
	*x = TenantRequest{}
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantRequest) ProtoMessage() {}

func (x *TenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantRequest.ProtoReflect.Descriptor instead.
func (*TenantRequest) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_tenants_proto_rawDescGZIP(), []int{2}
}

func (x *TenantRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

type DeleteUsersTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsersIds      []int64                `protobuf:"varint,1,rep,packed,name=usersIds,proto3" json:"usersIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUsersTenantsRequest) Reset() {
	*x = DeleteUsersTenantsRequest{}
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUsersTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUsersTenantsRequest) ProtoMessage() {}

func (x *DeleteUsersTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUsersTenantsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUsersTenantsRequest) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_tenants_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteUsersTenantsRequest) GetUsersIds() []int64 {
	if x != nil {
		return x.UsersIds
	}
	return nil
}

type ListTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	OwnerId       int64                  `protobuf:"varint,1,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Paginate      *v1.PaginateRequest    `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_tenants_proto_rawDescGZIP(), []int{4}
}

func (x *ListTenantsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListTenantsRequest) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *ListTenantsRequest) GetPaginate() *v1.PaginateRequest {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type ListTenantsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*Tenant              `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	Paginate      *v1.PaginateReply      `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsReply) Reset() {
	*x = ListTenantsReply{}
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsReply) ProtoMessage() {}

func (x *ListTenantsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsReply.ProtoReflect.Descriptor instead.
func (*ListTenantsReply) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_tenants_proto_rawDescGZIP(), []int{5}
}

func (x *ListTenantsReply) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *ListTenantsReply) GetPaginate() *v1.PaginateReply {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type TransferOwnershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      int64                  `protobuf:"varint,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	NewOwnerId    int64                  `protobuf:"varint,2,opt,name=newOwnerId,proto3" json:"newOwnerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferOwnershipRequest) Reset() {
	*x = TransferOwnershipRequest{}
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferOwnershipRequest) ProtoMessage() {}

func (x *TransferOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferOwnershipRequest.ProtoReflect.Descriptor instead.
func (*TransferOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_tenants_proto_rawDescGZIP(), []int{6}
}

func (x *TransferOwnershipRequest) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *TransferOwnershipRequest) GetNewOwnerId() int64 {
	if x != nil {
		return x.NewOwnerId
	}
	return 0
}

type GetReferredTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paginate      *v1.PaginateRequest    `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferredTenantsRequest) Reset() {
	*x = GetReferredTenantsRequest{}
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferredTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferredTenantsRequest) ProtoMessage() {}

func (x *GetReferredTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_tenants_v1_tenants_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferredTenantsRequest.ProtoReflect.Descriptor instead.
func (*GetReferredTenantsRequest) Descriptor() ([]byte, []int) {
	return file_api_tenants_v1_tenants_proto_rawDescGZIP(), []int{7}
}

func (x *GetReferredTenantsRequest) GetPaginate() *v1.PaginateRequest {
	if x != nil {
		return x.Paginate
	}
	return nil
}

var File_api_tenants_v1_tenants_proto protoreflect.FileDescriptor

const file_api_tenants_v1_tenants_proto_rawDesc = "" +
	"\n" +
	"\x1capi/tenants/v1/tenants.proto\x12\n" +
	"tenants.v1\x1a\x19api/utils/v1/models.proto\x1a\x1bapi/tenants/v1/models.proto\"s\n" +
	"\x13CreateTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12$\n" +
	"\vreferred_by\x18\x03 \x01(\x03H\x00R\n" +
	"referredBy\x88\x01\x01B\x0e\n" +
	"\f_referred_by\"E\n" +
	"\x13UpdateTenantRequest\x12\x1a\n" +
	"\btenantId\x18\x01 \x01(\x03R\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"+\n" +
	"\rTenantRequest\x12\x1a\n" +
	"\btenantId\x18\x01 \x01(\x03R\btenantId\"7\n" +
	"\x19DeleteUsersTenantsRequest\x12\x1a\n" +
	"\busersIds\x18\x01 \x03(\x03R\busersIds\"}\n" +
	"\x12ListTenantsRequest\x12\x16\n" +
	"\x06userId\x18\x03 \x01(\x03R\x06userId\x12\x18\n" +
	"\aownerId\x18\x01 \x01(\x03R\aownerId\x125\n" +
	"\bpaginate\x18\x02 \x01(\v2\x19.utils.v1.PaginateRequestR\bpaginate\"u\n" +
	"\x10ListTenantsReply\x12,\n" +
	"\atenants\x18\x01 \x03(\v2\x12.tenants.v1.TenantR\atenants\x123\n" +
	"\bpaginate\x18\x02 \x01(\v2\x17.utils.v1.PaginateReplyR\bpaginate\"V\n" +
	"\x18TransferOwnershipRequest\x12\x1a\n" +
	"\btenantId\x18\x01 \x01(\x03R\btenantId\x12\x1e\n" +
	"\n" +
	"newOwnerId\x18\x02 \x01(\x03R\n" +
	"newOwnerId\"R\n" +
	"\x19GetReferredTenantsRequest\x125\n" +
	"\bpaginate\x18\x01 \x01(\v2\x19.utils.v1.PaginateRequestR\bpaginate2\xee\x04\n" +
	"\aTenants\x12H\n" +
	"\fCreateTenant\x12\x1f.tenants.v1.CreateTenantRequest\x1a\x17.tenants.v1.TenantReply\x12H\n" +
	"\fUpdateTenant\x12\x1f.tenants.v1.UpdateTenantRequest\x1a\x17.tenants.v1.TenantReply\x12?\n" +
	"\fDeleteTenant\x12\x19.tenants.v1.TenantRequest\x1a\x14.utils.v1.EmptyReply\x12Q\n" +
	"\x12DeleteUsersTenants\x12%.tenants.v1.DeleteUsersTenantsRequest\x1a\x14.utils.v1.EmptyReply\x12?\n" +
	"\tGetTenant\x12\x19.tenants.v1.TenantRequest\x1a\x17.tenants.v1.TenantReply\x12K\n" +
	"\vListTenants\x12\x1e.tenants.v1.ListTenantsRequest\x1a\x1c.tenants.v1.ListTenantsReply\x12R\n" +
	"\x11TransferOwnership\x12$.tenants.v1.TransferOwnershipRequest\x1a\x17.tenants.v1.TenantReply\x12Y\n" +
	"\x12GetReferredTenants\x12%.tenants.v1.GetReferredTenantsRequest\x1a\x1c.tenants.v1.ListTenantsReplyBQ\n" +
	"\n" +
	"tenants.v1P\x01ZAgitlab.calendaria.team/services/tenants/api/tenants/v1;tenants_v1b\x06proto3"

var (
	file_api_tenants_v1_tenants_proto_rawDescOnce sync.Once
	file_api_tenants_v1_tenants_proto_rawDescData []byte
)

func file_api_tenants_v1_tenants_proto_rawDescGZIP() []byte {
	file_api_tenants_v1_tenants_proto_rawDescOnce.Do(func() {
		file_api_tenants_v1_tenants_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_tenants_v1_tenants_proto_rawDesc), len(file_api_tenants_v1_tenants_proto_rawDesc)))
	})
	return file_api_tenants_v1_tenants_proto_rawDescData
}

var file_api_tenants_v1_tenants_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_tenants_v1_tenants_proto_goTypes = []any{
	(*CreateTenantRequest)(nil),       // 0: tenants.v1.CreateTenantRequest
	(*UpdateTenantRequest)(nil),       // 1: tenants.v1.UpdateTenantRequest
	(*TenantRequest)(nil),             // 2: tenants.v1.TenantRequest
	(*DeleteUsersTenantsRequest)(nil), // 3: tenants.v1.DeleteUsersTenantsRequest
	(*ListTenantsRequest)(nil),        // 4: tenants.v1.ListTenantsRequest
	(*ListTenantsReply)(nil),          // 5: tenants.v1.ListTenantsReply
	(*TransferOwnershipRequest)(nil),  // 6: tenants.v1.TransferOwnershipRequest
	(*GetReferredTenantsRequest)(nil), // 7: tenants.v1.GetReferredTenantsRequest
	(*v1.PaginateRequest)(nil),        // 8: utils.v1.PaginateRequest
	(*Tenant)(nil),                    // 9: tenants.v1.Tenant
	(*v1.PaginateReply)(nil),          // 10: utils.v1.PaginateReply
	(*TenantReply)(nil),               // 11: tenants.v1.TenantReply
	(*v1.EmptyReply)(nil),             // 12: utils.v1.EmptyReply
}
var file_api_tenants_v1_tenants_proto_depIdxs = []int32{
	8,  // 0: tenants.v1.ListTenantsRequest.paginate:type_name -> utils.v1.PaginateRequest
	9,  // 1: tenants.v1.ListTenantsReply.tenants:type_name -> tenants.v1.Tenant
	10, // 2: tenants.v1.ListTenantsReply.paginate:type_name -> utils.v1.PaginateReply
	8,  // 3: tenants.v1.GetReferredTenantsRequest.paginate:type_name -> utils.v1.PaginateRequest
	0,  // 4: tenants.v1.Tenants.CreateTenant:input_type -> tenants.v1.CreateTenantRequest
	1,  // 5: tenants.v1.Tenants.UpdateTenant:input_type -> tenants.v1.UpdateTenantRequest
	2,  // 6: tenants.v1.Tenants.DeleteTenant:input_type -> tenants.v1.TenantRequest
	3,  // 7: tenants.v1.Tenants.DeleteUsersTenants:input_type -> tenants.v1.DeleteUsersTenantsRequest
	2,  // 8: tenants.v1.Tenants.GetTenant:input_type -> tenants.v1.TenantRequest
	4,  // 9: tenants.v1.Tenants.ListTenants:input_type -> tenants.v1.ListTenantsRequest
	6,  // 10: tenants.v1.Tenants.TransferOwnership:input_type -> tenants.v1.TransferOwnershipRequest
	7,  // 11: tenants.v1.Tenants.GetReferredTenants:input_type -> tenants.v1.GetReferredTenantsRequest
	11, // 12: tenants.v1.Tenants.CreateTenant:output_type -> tenants.v1.TenantReply
	11, // 13: tenants.v1.Tenants.UpdateTenant:output_type -> tenants.v1.TenantReply
	12, // 14: tenants.v1.Tenants.DeleteTenant:output_type -> utils.v1.EmptyReply
	12, // 15: tenants.v1.Tenants.DeleteUsersTenants:output_type -> utils.v1.EmptyReply
	11, // 16: tenants.v1.Tenants.GetTenant:output_type -> tenants.v1.TenantReply
	5,  // 17: tenants.v1.Tenants.ListTenants:output_type -> tenants.v1.ListTenantsReply
	11, // 18: tenants.v1.Tenants.TransferOwnership:output_type -> tenants.v1.TenantReply
	5,  // 19: tenants.v1.Tenants.GetReferredTenants:output_type -> tenants.v1.ListTenantsReply
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_tenants_v1_tenants_proto_init() }
func file_api_tenants_v1_tenants_proto_init() {
	if File_api_tenants_v1_tenants_proto != nil {
		return
	}
	file_api_tenants_v1_models_proto_init()
	file_api_tenants_v1_tenants_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_tenants_v1_tenants_proto_rawDesc), len(file_api_tenants_v1_tenants_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_tenants_v1_tenants_proto_goTypes,
		DependencyIndexes: file_api_tenants_v1_tenants_proto_depIdxs,
		MessageInfos:      file_api_tenants_v1_tenants_proto_msgTypes,
	}.Build()
	File_api_tenants_v1_tenants_proto = out.File
	file_api_tenants_v1_tenants_proto_goTypes = nil
	file_api_tenants_v1_tenants_proto_depIdxs = nil
}
