// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: api/tenants/v1/tenants.proto

package tenants_v1

import (
	context "context"
	v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Tenants_CreateTenant_FullMethodName        = "/tenants.v1.Tenants/CreateTenant"
	Tenants_UpdateCurrentTenant_FullMethodName = "/tenants.v1.Tenants/UpdateCurrentTenant"
	Tenants_DeleteCurrentTenant_FullMethodName = "/tenants.v1.Tenants/DeleteCurrentTenant"
	Tenants_GetCurrentTenant_FullMethodName    = "/tenants.v1.Tenants/GetCurrentTenant"
	Tenants_ListTenants_FullMethodName         = "/tenants.v1.Tenants/ListTenants"
)

// TenantsClient is the client API for Tenants service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TenantsClient interface {
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*TenantReply, error)
	UpdateCurrentTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*TenantReply, error)
	DeleteCurrentTenant(ctx context.Context, in *v1.EmptyRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error)
	GetCurrentTenant(ctx context.Context, in *v1.EmptyRequest, opts ...grpc.CallOption) (*TenantReply, error)
	ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsReply, error)
}

type tenantsClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantsClient(cc grpc.ClientConnInterface) TenantsClient {
	return &tenantsClient{cc}
}

func (c *tenantsClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*TenantReply, error) {
	out := new(TenantReply)
	err := c.cc.Invoke(ctx, Tenants_CreateTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsClient) UpdateCurrentTenant(ctx context.Context, in *UpdateTenantRequest, opts ...grpc.CallOption) (*TenantReply, error) {
	out := new(TenantReply)
	err := c.cc.Invoke(ctx, Tenants_UpdateCurrentTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsClient) DeleteCurrentTenant(ctx context.Context, in *v1.EmptyRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error) {
	out := new(v1.EmptyReply)
	err := c.cc.Invoke(ctx, Tenants_DeleteCurrentTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsClient) GetCurrentTenant(ctx context.Context, in *v1.EmptyRequest, opts ...grpc.CallOption) (*TenantReply, error) {
	out := new(TenantReply)
	err := c.cc.Invoke(ctx, Tenants_GetCurrentTenant_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantsClient) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsReply, error) {
	out := new(ListTenantsReply)
	err := c.cc.Invoke(ctx, Tenants_ListTenants_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantsServer is the server API for Tenants service.
// All implementations must embed UnimplementedTenantsServer
// for forward compatibility
type TenantsServer interface {
	CreateTenant(context.Context, *CreateTenantRequest) (*TenantReply, error)
	UpdateCurrentTenant(context.Context, *UpdateTenantRequest) (*TenantReply, error)
	DeleteCurrentTenant(context.Context, *v1.EmptyRequest) (*v1.EmptyReply, error)
	GetCurrentTenant(context.Context, *v1.EmptyRequest) (*TenantReply, error)
	ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsReply, error)
	mustEmbedUnimplementedTenantsServer()
}

// UnimplementedTenantsServer must be embedded to have forward compatible implementations.
type UnimplementedTenantsServer struct {
}

func (UnimplementedTenantsServer) CreateTenant(context.Context, *CreateTenantRequest) (*TenantReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedTenantsServer) UpdateCurrentTenant(context.Context, *UpdateTenantRequest) (*TenantReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCurrentTenant not implemented")
}
func (UnimplementedTenantsServer) DeleteCurrentTenant(context.Context, *v1.EmptyRequest) (*v1.EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCurrentTenant not implemented")
}
func (UnimplementedTenantsServer) GetCurrentTenant(context.Context, *v1.EmptyRequest) (*TenantReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentTenant not implemented")
}
func (UnimplementedTenantsServer) ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTenants not implemented")
}
func (UnimplementedTenantsServer) mustEmbedUnimplementedTenantsServer() {}

// UnsafeTenantsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantsServer will
// result in compilation errors.
type UnsafeTenantsServer interface {
	mustEmbedUnimplementedTenantsServer()
}

func RegisterTenantsServer(s grpc.ServiceRegistrar, srv TenantsServer) {
	s.RegisterService(&Tenants_ServiceDesc, srv)
}

func _Tenants_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenants_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenants_UpdateCurrentTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).UpdateCurrentTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenants_UpdateCurrentTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).UpdateCurrentTenant(ctx, req.(*UpdateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenants_DeleteCurrentTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).DeleteCurrentTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenants_DeleteCurrentTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).DeleteCurrentTenant(ctx, req.(*v1.EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenants_GetCurrentTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).GetCurrentTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenants_GetCurrentTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).GetCurrentTenant(ctx, req.(*v1.EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tenants_ListTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantsServer).ListTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Tenants_ListTenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantsServer).ListTenants(ctx, req.(*ListTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tenants_ServiceDesc is the grpc.ServiceDesc for Tenants service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tenants_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tenants.v1.Tenants",
	HandlerType: (*TenantsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTenant",
			Handler:    _Tenants_CreateTenant_Handler,
		},
		{
			MethodName: "UpdateCurrentTenant",
			Handler:    _Tenants_UpdateCurrentTenant_Handler,
		},
		{
			MethodName: "DeleteCurrentTenant",
			Handler:    _Tenants_DeleteCurrentTenant_Handler,
		},
		{
			MethodName: "GetCurrentTenant",
			Handler:    _Tenants_GetCurrentTenant_Handler,
		},
		{
			MethodName: "ListTenants",
			Handler:    _Tenants_ListTenants_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/tenants/v1/tenants.proto",
}
