image:
  # image config
  repository: 
  tag: 
  pullPolicy: IfNotPresent

fullnameOverride: tenants
nameOverride: tenants
namespaceOverride: stage-backend
configmap:
  private:
    enabled: false
  data:
    DEBUG: "1"
    SERVICE_NAME: "tenants"
    AUTOMIGRATE: "true"
    CONSUL_ADDRESS: "http://10.2.5.6:8500"
    VAULT_ADDRESS: "http://10.2.4.5:8200"
    VAULT_ROLE_ID: "2b3650aa-640f-a0aa-f38a-ac23005acdac"
    VAULT_SECRET_ID: "d77d8a29-3099-ca08-9e6d-d9d23911c63d"

server:
  replicaCount: 1
  command: ["./tenants", "-conf", "./config.yaml"]
  podSecurityContext: {}
  securityContext: {}
  serviceAccount:

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 0.5
      memory: 0.5Gi

  service:
    type: ClusterIP
    port: 80
    targetPort: 8000

  ingress:
    enabled: false
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 512m
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /tenants/?(.*)
    hosts:
      - stage.calendaria.net
    tls:
    - secretName: calendaria-tls
      hosts:
        - stage.calendaria.net

  nodeSelector: {}
  tolerations: []
  affinity: {}

migrateJob:
  enabled: true
  command: ["/atlas", "migrate", "apply", "--url", "postgres://tenants:oow6uya6aeX=oto@10.2.8.175:5432/tenants?search_path=public"]

